- lib/CMakeLists.txt
Reduces repitition in CMakeLists.txt.  Individiual tests can be selected
via gtest flags.
> lib: combine 7series tests into a single target

- fuzzers/070-tileconn/generate.py
With this additional rules we now have loop-free routing nodes for the artix7 and kintex7 ROIs.
> Add missing blacklist rules to tileconn fuzzer

- CMakeLists.txt
- README.md
Running 'make go' with no options will generate a Release build (-O3, no debug info, etc).  Debug builds (-O0 -g) can be built by running 'cmake -DCMAKE_BUILD_TYPE=Debug ..' in the build directory.  Tests are not built by default.  To build them, add -DPRXRAY_BUILD_TESTING=ON to the cmake command line.
> Fix default build settings

- lib/CMakeLists.txt
- lib/include/prjxray/xilinx/xc7series/configuration.h
- lib/include/prjxray/xilinx/xc7series/configuration_packetizer.h
- lib/xilinx/xc7series/configuration_packetizer.cc
- lib/xilinx/xc7series/configuration_packetizer_test.cc
ConfigurationPacketizer translates a Configuration's frame data to a
sequence of ConfigurationPackets that will write that configuration to
the configuration's Part.
> lib: xc7series: generate packets from a Configuration

- minitests/util/runme.tcl
This forces better ROI to outside separation. I haven't tested this extensively, but this would only effect the minitests if there are any issues
> minitests: flatten hiearchy

- lib/include/prjxray/xilinx/xc7series/bitstream_writer.h
- lib/include/prjxray/xilinx/xc7series/command.h
- lib/include/prjxray/xilinx/xc7series/configuration_options_0_value.h
- lib/include/prjxray/xilinx/xc7series/configuration_packet_with_payload.h
- lib/include/prjxray/xilinx/xc7series/configuration_register.h
- lib/include/prjxray/xilinx/xc7series/nop_packet.h
- lib/xilinx/xc7series/bitstream_writer.cc
- lib/xilinx/xc7series/bitstream_writer_test.cc
- minitests/partial_reconfig_flow/Makefile
- minitests/roi_harness/fasm2bit.sh
- tools/CMakeLists.txt
- tools/xc7patch.cc
As a quick solution to demonstrate the toolchain working, xc7patch only generates the data frame writes.  The required init and final sequences needed for programming into a part are directly copied over from the Vivado-generated harness.  This is fragile as the exact offsets of the sequences are likely to change with Vivado version changes.
This series generates an equivalent init and final sequence as part of xc7patch which results in a directly usable output bitstream.  Further, the Xilinx BIT header has been added as well which means the resulting bitstream can be programming normally via Vivado's Hardware Manager, iMPACT, and OpenOCD.
> Replace init/final sequence hacks with less hacky solution

- Dockerfile
Resolves #101 
Per https://github.com/docker-library/official-images/issues/3835,
multi-arch official images are currently updated as each architecture's
builder finishes. This leads to times when the latest tags only have a
few architectures available.  Since our builds only happen on amd64,
pull nginx from the amd64 namespace specifically to avoid the problem.
Signed-off-by: Rick Altherr <kc8apf@kc8apf.net>
> Force amd64 image for nginx

- fuzzers/074-dump_all/reduce_tile_types.py
- prjxray/db.py
- prjxray/grid.py
- prjxray/lib.py
- prjxray/site_type.py
- prjxray/tile.py
- tools/quick_test.py
All data from #125 is now exported from the prjxray library.  A bug was found in how site reduction was done, so some sites in some tile types don't round trip.  This can be fixed in a future PR.
> Add methods to prjxray library.

- CMakeLists.txt
> cmake: Only add `-Wall and -Werror` for our code.

- fuzzers/015-clbnffmux/generate.py
- fuzzers/016-clbnoutmux/generate.py
- fuzzers/018-clbram/generate.py
- prjxray/util.py
The following have assertions, but have existing issues and so were not touched:
- 051-imuxlout
- 052-clkin
- 053-ctrlin
- 057-bipips
> fuzzers: remove db assert where possible

- fuzzers/007-timing/minitest/test_unique/generate.tcl
- fuzzers/007-timing/projects/oneblinkw/generate.tcl
- fuzzers/007-timing/projects/picorv32/generate.tcl
- fuzzers/007-timing/projects/placelut/generate.tcl
- fuzzers/007-timing/projects/placelut_fb/generate.tcl
- fuzzers/007-timing/projects/placelut_ff_fb/generate.tcl
- fuzzers/011-ffconfig/generate.tcl
- fuzzers/012-clbn5ffmux/generate.tcl
- fuzzers/013-clbncy0/generate.tcl
- fuzzers/014-ffsrcemux/generate.tcl
- fuzzers/015-clbnffmux/generate.tcl
- fuzzers/016-clbnoutmux/generate.tcl
- fuzzers/017-clbprecyinit/generate.tcl
- fuzzers/018-clbram/generate.tcl
- fuzzers/019-ndi1mux/generate.tcl
- fuzzers/101-bram-config/generate.tcl
- fuzzers/101-bram-config/minitest/runme.tcl
- fuzzers/102-bram-data/generate.tcl
- minitests/clbconfigs/runme.tcl
- minitests/picorv32-v/runme.tcl
- minitests/picorv32-y/runme.tcl
- minitests/util/runme.tcl
Fixes: https://github.com/SymbiFlow/prjxray/issues/212
A recent change got the ROI X/Y out of sync with the ROI primitives. This caused issues for many fuzzers which used EXCLUDE_PLACEMENT to create a sharp boundary between the ROI and the rest of the FPGA. This is problematic because the site ROI was expanded to include most of the chip, and this precluded placing harness test logic in the top module.
Really, we need to separate out the ROI that we are using for tilegrid generation vs fuzzers. Or, if the idea is to no longer use an ROI for tilegrid, we should just remove the ROI entirely from that fuzzer
> fuzzers: don't use EXCLUDE_PLACEMENT on ROI

- fuzzers/018-clbram/Makefile
- fuzzers/018-clbram/generate.py
- fuzzers/018-clbram/generate.tcl
- fuzzers/018-clbram/top.py
Fixes https://github.com/SymbiFlow/prjxray/issues/293
As this tcl script is currently written design is allowed to PnR the harness LFSR into the ROI. This causes some solves to get messed up as unexpected LUTs are added. I worked around by dumping the actual LUTs used from tcl and dropping that site if the LUTs don't match the expectation. There is a pblock exclude flag we are using in some tcl scripts that we might be able to use alternatively, but this is probably more proper since the flag was unreliable.
I also found an issue with WEMUX.CE failing to solve in rare scenarios caused by a module name typo
> clbram: ignore unexpected LUT contents

- fuzzers/int_maketodo.py
This regression caused by originally we worked on the pushed db, which ran mergedb.sh on it (filters out unresolved entries)
> int_maketodo: only count resolved tags

- fuzzers/050-intpips/Makefile
Regression from some code cleanup. Its trying to look at the current iteration, which hasn't been completed yet. Instead it should look at the previous iteration, cached in build_dir
> intpips: todo look at last iter, not iter not yet completed

- fuzzers/056-rempips/generate.tcl
Fixes https://github.com/SymbiFlow/prjxray/issues/331
I had a "bad path" failure after, but this is because of https://github.com/SymbiFlow/prjxray/issues/332
> rempips: fix todo.txt path

- fuzzers/005-tilegrid/Makefile
Some of our systems have /bin/sh as bash, some as dash. So far this hasn't been an issue. However, I recently used {a,b} notation, which evidently doesn't work in dash. Seems the simplest option is to just revert this. We can think about setting SHELL or such later if it becomes problematic
> tilegrid: /bin/dash compatibility

- fuzzers/050-intpips/Makefile
- fuzzers/056-rempips/generate.py
- fuzzers/int_loop.mk
- fuzzers/int_loop.sh
Odd. I thought I had fixed this, but evidently not. Regression from saving all the iterations, which adds another directory level. I think this bug only exists when you ran "make" outside of "make run", but I've also updated Makefiles to fix that as well
I've also sorted todo_all.txt to make diffing iterations easier
> rempips: fix todo path

- fuzzers/050-intpips/Makefile
- fuzzers/int_loop.mk
- prjxray/util.py
- utils/dbfixup.py
Fixes https://github.com/SymbiFlow/prjxray/issues/363
Regression from moving dbfixup to db instead of pushdb target. This is due to MERGEDB implicitly/silently filtering out unresolved entries. Solved by making --clb-int allow dropping unresolved entries, since this type of fuzzer often has them
> Dbfixup fix

- tools/CMakeLists.txt
- tools/gen_part_base_yaml.cc
This PR add possibility to analyze FAR registers in the bitstream
> gen_part_base_yaml.cc: Added the possibility to read FAR registers

- fuzzers/reseg.sh
generate.py is build dir only, but segmatch was greedy match on everything
> reseg: segmatch only build dir

- fuzzers/050-intpips/Makefile
Although the "database" target is usually very quick in these makefiles (say 1 to 10 specimens), intpips has around 250. This makes this step take considerably longer than other targets. This adds parallelism to significantly speed up this step. Note that most of the time is spent in specimen generation, but this step is still not insignificant.
> intpips: parallelize db build

- fuzzers/058-hclkpips/generate.py
- fuzzers/058-hclkpips/generate.tcl
Mitigation for https://github.com/SymbiFlow/prjxray/issues/392
Still testing a bit, but "probably works". Solves the issue for now by selecting a different tile to play with. The current tile is at the far left, which is currently unsolved. By selecting the last tile, we are at the right (I think) which is currently solved
> hclkpips: HCLK bitstream workaround

- fuzzers/055-gnd/Makefile
- fuzzers/055-gnd/generate.tcl
This was a bad interaction with some stale files, causing mismatch between my local builds and the build server
> 055-gnd: fix bad makefile target

- fuzzers/001-part-yaml/Makefile.specimen
- fuzzers/001-part-yaml/generate.tcl
This PR modifies fuzzer 001 to use PERFRAMECRC botstream for xc7z family. This PR should be merged after the #375 is merged.
> 001-part-yaml: Modified script and tools to generate Zynq YAML.

- .gitignore
- README.md
- database/artix7/settings.sh
- database/kintex7/settings.sh
- database/zynq7/settings.sh
- settings/artix7.sh
- settings/kintex7.sh
- settings/zynq7.sh
The fuzzers are dependent on the contents of `settings.sh` and hence the file needs to be kept in sync with the fuzzers. The database is not necessarily kept in sync with the fuzzers, hence the settings.sh files are in the wrong place.
> Move settings out of database directory into new settings directory.

- tests/test_util.py
Hi John (or anyone else),
This is a basic test of what we discussed at 35C3, testing from prjxray.util import get_roi, get_roi().gen_sites() for two trivial cases: a database with a single tile and either no sites (empty sites dictionary) or a single site.
I made it so it's easy to add more tests.
HTH
Alon
> add a basic test of prjxray.util.get_row().gen_sites()

- fuzzers/fuzzer.mk
- utils/genheader.sh
- utils/top_generate.mk
- utils/top_generate.sh
This significantly speeds up certain development work by not running vivado generate when only post processing needs to be re-run. Dependencies are not perfect either, but its not worse than it was before
> top_generate.sh => top_generate.mk

- prjxray/bitstream.py
- prjxray/util.py
- utils/addrwidth.py
Prints out part yaml addresses as full 32 bit addresses instead of composite parts
> addrwidth utility

- prjxray/util.py
Fixes error if prjxray.db is imported directly:
```
$ python3
Python 3.5.4rc1 (default, Jul 25 2017, 08:53:34) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import prjxray.db
Traceback (most recent call last):
File "<console>", line 1, in <module>
File "/usr/local/google/home/keithrothman/cat_x/prjxray/prjxray/db.py", line 3, in <module>
from prjxray import grid
File "/usr/local/google/home/keithrothman/cat_x/prjxray/prjxray/grid.py", line 3, in <module>
from prjxray import segment_map
File "/usr/local/google/home/keithrothman/cat_x/prjxray/prjxray/segment_map.py", line 2, in <module>
from prjxray import bitstream
File "/usr/local/google/home/keithrothman/cat_x/prjxray/prjxray/bitstream.py", line 3, in <module>
from prjxray import util …
```
> Remove circular import dependency.

- fuzzers/005-tilegrid/add_tdb.py
This PR solves issue #481. add_tdb.py now checks if all the bits in a same tag have the same base address and, if that is the case, the first of them is selected.
> 005-tilegrid/add_tdb.py: added frame check

- fuzzers/int_create_empty_db.sh
- fuzzers/int_loop.mk
05x series were failing when no DB was present. This prevented those fuzzers from being run separately. This PR fixes that.
> fuzzers: int: create empty DB if it doesn't exist

- fuzzers/051-pip-imuxlout/generate.tcl
- fuzzers/int_loop.mk
- fuzzers/piplist.tcl
Recently imuxlout got some rework which included things like adding a riscv and increasing the batch size from 10 to 50 pips. I suspected this might be slowing down quick runs, so I looked into tuning to keep builds fast
Results:
* QUICK=N: IP
* QUICK=Y (pre-commit): ? not sure if recorded
* Also reduce todo from 50 to 3: real    5m45.993s
* Also reduce the number of tiles we dump: real    2m24.778s
Although this was primarily targeted at 50, the first optimization should also reduce other fuzzers from 10 to 3, which should speed them up slightly.
> pip (especially imuxlout) quick

- fuzzers/int_loop.mk
copying in seeded target was missed in #500. This PR fixes that
> fuzzers: int_loop: create empty DB also in seeded target

- fuzzers/015-clb-nffmux/Makefile
- fuzzers/016-clb-noutmux/Makefile
Some INT bits were getting matched into the NFFMUX and NOUTMUX fuzzers.  Increasing N to 3 appears to prevent this.
> Increase N for NFFMUX and NOUTMUX to prevent false matches.

- fuzzers/005-tilegrid/Makefile
- fuzzers/005-tilegrid/add_tdb.py
- fuzzers/005-tilegrid/generate_full.py
- fuzzers/005-tilegrid/util.py
This PR is to solve #495.
I have added a way to propagate INT_L base addresses which do not have an adjacent block (In this case the INT_L_X0Y* interconnects) of the top fabric row. 
There is also the need to do the same for the bottom CMT column, given that the PS7 is attached to all the left interconnects of the FPGA fabric.
> 005-tilegrid/generate_full: propagating INT_L base addrs

- fuzzers/011-clb-ffconfig/top.py
- fuzzers/012-clb-n5ffmux/top.py
- fuzzers/013-clb-ncy0/top.py
- fuzzers/014-clb-ffsrcemux/top.py
- fuzzers/015-clb-nffmux/top.py
- fuzzers/016-clb-noutmux/top.py
- fuzzers/017-clb-precyinit/top.py
- fuzzers/018-clb-ram/top.py
- fuzzers/019-clb-ndi1mux/top.py
- fuzzers/clb.mk
- fuzzers/fuzzer.mk
This PR solves https://github.com/SymbiFlow/prjxray/issues/534 issue and issues related to the CLB fuzzers for which the segmatch solver is unable to find a solution.
Basically the CLB fuzzers are now re-run whenever the pushdb fails because of a bad db file generation.
The top.py of the CLB fuzzers now adds to the CLBN variable an increment calculated in the clb.mk file.
The increment allows to have an higher probability of getting a suitable design for the fuzzer.
Mainly this was done to ensure the correct clb .db file generation with targets that do require more CLBs to be instantiated.
> 01x CLB rerun if pushdb fails

- fuzzers/050-pip-seed/generate.py
- fuzzers/055-pip-gnd/generate.py
- fuzzers/int_generate.py
- prjxray/bitfilter.py
Also prohibit matching VCC_WIRE pips, they are expected to all be default PIPs.
> Filter some CLB bits that the INT fuzzers tend to include due to high correlation

- minitests/roi_harness/runme.sh
The scripts do not have execution rights, so the build fails on calling them.
Explicit interpreter call solves the issue.
Signed-off-by: Karol Gugala <kgugala@antmicro.com>
> minitests: ROI harness: call python interpreter explicitly

- fuzzers/Makefile
Fixes #568 . At least for a clean build.
> Fuzzers: Makefile: use single colon target for run.ok targets

- prjxray/bitstream.py
- prjxray/fasm_disassembler.py
Before the code would remove bits as they were matched.  As a result as bits were removed, 0-bit features started to match.
> Handle 0-bit features correctly.

- fuzzers/Makefile
The `generate_grid.py` tool requires tilegrid.json to run.
Fixes #601.
> fuzzers: 074-dump_all depends on 005-tilegrid.

- prjxray/fasm_disassembler.py
> Use hashable data types for FasmLine output.

- prjxray/util.py
- utils/checkdb.py
This PR is to solve two issues:
- https://github.com/SymbiFlow/prjxray/issues/583: I have noticed that all the tiles are being checked. I have also seen that all the tiles with the same `tile_type` share the same bits, making it highly time consuming if there is the need to check every single one of them. This way the script is much faster, but I am not sure it is the best solution, because maybe some tiles of the same type have differences.
- https://github.com/SymbiFlow/prjxray/issues/575: during the extraction of the bits there is an assertion that checks whether the bit is consistent with the `frames` number of the tile.
> checkdb: optimized script and added out-of-bound check

- utils/checkdb.py
This PR is to restore the check on all the previous tiles instead of only the ones related to the same `tile_type`. The performance remains the same.
> checkdb.py: restored check on all previous tiles

- fuzzers/074-dump_all/reduce_tile_types.py
- prjxray/lib.py
This PR is to solve https://github.com/SymbiFlow/prjxray/issues/134. The naming was wrong because there was the assumption that all the sites in a tile were equal and had adjacent locations in the grid. This is untrue for some kind of tiles such as `BRAM`, `DSP` and some `CMT` related tile. 
With this fix the min_coordinated used to reduce all the site coordinates is calculated for each single `group` of sites in every tile.
> 074-dump-all: stabilized naming of sites

- fuzzers/005-tilegrid/bram/Makefile
- fuzzers/005-tilegrid/bram/top.py
- fuzzers/005-tilegrid/bram_block/Makefile
- fuzzers/005-tilegrid/bram_block/generate.tcl
- fuzzers/005-tilegrid/bram_block/top.py
- fuzzers/005-tilegrid/bram_int/Makefile
- fuzzers/005-tilegrid/clb/Makefile
- fuzzers/005-tilegrid/clb/top.py
- fuzzers/005-tilegrid/clb_int/Makefile
- fuzzers/005-tilegrid/clb_int/top.py
- fuzzers/005-tilegrid/clk_hrow/top.py
- fuzzers/005-tilegrid/dsp/Makefile
- fuzzers/005-tilegrid/dsp/top.py
- fuzzers/005-tilegrid/dsp_int/Makefile
- fuzzers/005-tilegrid/fifo_int/Makefile
- fuzzers/005-tilegrid/iob/Makefile
- fuzzers/005-tilegrid/iob/generate.tcl
- fuzzers/005-tilegrid/iob/top.py
- fuzzers/005-tilegrid/iob_int/Makefile
- fuzzers/005-tilegrid/mmcm/Makefile
- fuzzers/005-tilegrid/mmcm/top.py
- fuzzers/005-tilegrid/monitor/top.py
- fuzzers/005-tilegrid/pll/Makefile
- fuzzers/005-tilegrid/pll/generate.tcl
- fuzzers/005-tilegrid/pll/top.py
- prjxray/util.py
- gen_fuzz_states now generates all states in log2(N) + 2 samples
- Sorting tile names ensures deterministic matching between gen_fuzz_states and sites, which is required for deterministic solutions
- Lowers sample count to log2(Nmax) + 2 samples.  Nmax is set to max count across all 7-series parts
- Modified IOB and PLL fuzzer to be deterministic
> Sort tiles and revamp gen_fuzz_states to be more efficient.

- fuzzers/041-clk-hrow-pips/Makefile
- fuzzers/041-clk-hrow-pips/top.py
Zync part selected is missing some side clock connections, so solving those bits are impossible.  The selected artix and kintex parts do not have this issue.
> Limit target pips on zync to avoid unsolvable bits.

- prjxray/tile.py
- utils/quick_test.py
This PR allows `get_isntance_sites` not to break with the https://github.com/SymbiFlow/prjxray/pull/644 changes, this because the `find_origin_coordinate` in `lib.py` has changed.
the `quick_test` still does not work with the upstream db version because the `074-dump-all` fuzzer should be run with the fixes.
> tile.py: changed get_instance_sites function

- .github/kokoro/db-full.sh
- fuzzers/Makefile
Previous CI logic deleted logs files along with intermediate outputs
from fuzzers.  This makes debugging issues like #661 harder.
> Save fuzzer logs, even on success.

- fuzzers/058-pip-hclk/Makefile
- tools/segmatch.cc
This PR is to get en error if segmatch does not find the input file as suggested in https://github.com/SymbiFlow/prjxray/pull/630. This solves https://github.com/SymbiFlow/prjxray/issues/338
> segmatch.cpp: if f_in does not exits returns -1

- htmlgen/htmlgen.py
Before;
```
CLBLL_L.SLICEL_X1.A5FFMUX
Bit Name                        Position
CLBLL_L.SLICEL_X1.A5FFMUX.IN_A  31_08
CLBLL_L.SLICEL_X1.A5FFMUX.IN_B  31_11
```
After;
```
PIPs driving CLBLL_L.SLICEL_X0.B5FFMUX
PIP                            30_18  30_19
CLBLL_L.SLICEL_X0.B5FFMUX.IN_B   1      -
CLBLL_L.SLICEL_X0.B5FFMUX.IN_A   -      1
```
> Fix the output of internal routing MUXs in the CLBs.

- settings/artix7.sh
This PR solves the missing BRKH_INT tiles while building `picosoc`. The `roi-harness` has to be regenerated.
> artix7.sh: shrinking Y_MAX to exclude BRKH tiles

- prjxray/site_type.py
[INOUT is found on the PS7 interface on the Zynq](https://github.com/SymbiFlow/prjxray-db/blob/b9c0324464e4b00f122ea2dc23b24ee2bad50fa7/zynq7/site_type_PS7.json#L2-L46).
> prjxray: Add INOUT to direction enum.

- lib/CMakeLists.txt
- lib/include/prjxray/xilinx/xc7series/frames.h
- lib/include/prjxray/xilinx/xc7series/utils.h
- lib/xilinx/xc7series/frames.cc
- lib/xilinx/xc7series/utils.cc
- tools/CMakeLists.txt
- tools/xc7frames2bit.cc
- tools/xc7patch.cc
The tool is a WIP, because there is some additional testing needed as the tool produces a bitstream that when converted to fasm contains a lot of non-converted bits. This is still under investigation.
Currently I used the following script and compared the fasm files.
<pre>
${XRAY_BIT2FASM} design.bit  > design.fasm
${XRAY_FASM2FRAMES} design.fasm design.frames
${XRAY_DIR}/build/tools/xc7frames2bit --part_name $XRAY_PART --part_file $XRAY_PART_YAML --frm_file design.frames --output_file design_frames2bit.bit
${XRAY_BIT2FASM} design_frames2bit.bit > design_frames2bit.fasm
</pre>
> Implement the xc7frames2bit tool

- fuzzers/055-pip-gnd/Makefile
- fuzzers/pip_loop.mk
This PR is to solve #626. 
I ran the fuzzers several times locally while working on the stabilization part and grepped for the:
<pre>
make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
</pre>
message.
After this fix the search didn't return any log, so I believe this solves the issue.
> Fix makefiles to pass -j option

- docs/Makefile
- docs/conf.py
```
Running Sphinx v1.8.5
/bin/sh: 1: cd: can't cd to db_dev_process/fuzzers
/bin/sh: 1: cd: can't cd to db_dev_process/fuzzers
Linking ../../../minitests/clb-bused/README.md
Missing ../../../minitests/clb-carry_cin_cyinit/README.md
Missing ../../../minitests/clb-configs/README.md
Linking ../../../minitests/clb-muxf8/README.md
Missing ../../../minitests/clkbuf/README.md
```
> docs: Trying to fix readthedocs

- lib/CMakeLists.txt
- lib/include/prjxray/xilinx/xc7series/ecc.h
- lib/xilinx/xc7series/ecc.cc
- lib/xilinx/xc7series/frames.cc
- lib/xilinx/xc7series/frames_test.cc
Issue #768 showed that there was a bug when filling in the configuration with empty frames. Instead of starting with frame 0 it started with the first frame in the frames file. If the frames file already contained frame with address 0x00000000 (which was usually the case) everything worked fine, but with a custom frames file that was missing frame 0 we ended up with incorrect frame addresses when comparing the results of bitread.
Note however, that this is not related to the bug in #768.
> xc7frames2bit: add missing frames starting with 0

- fuzzers/run_fuzzer.py
Retries can be re-enabled when #635 is fixed.
Currently the retries are just causing CI to take a long time.
> fuzzers: Disable retries by default.

- .github/kokoro/db-full.sh
- Makefile
- fuzzers/Makefile
- minitests/roi_harness/Makefile
These targets are for:
- Generating additional database outputs that are part, e.g. yaml files.
- Generating harnesses
Fixes #708
> Add make targets to build additional outputs from each database.

- lib/CMakeLists.txt
- lib/include/prjxray/xilinx/xc7series/configuration.h
- lib/include/prjxray/xilinx/xc7series/ecc.h
- lib/xilinx/xc7series/configuration_test.cc
- lib/xilinx/xc7series/ecc.cc
This PR is to solve #768 
xc7 bitstreams appear to have 2 frames of padding between rows.
This is taken into account in the Type2 configuration package creation: https://github.com/SymbiFlow/prjxray/blob/master/lib/xilinx/xc7series/utils.cc#L35
However, the condition in ``configuration.h`` that is used by bitread doesn't check the block_type nad top/bottom half conditions:
https://github.com/SymbiFlow/prjxray/blob/master/lib/include/prjxray/xilinx/xc7series/configuration.h#L152
This PR makes sure the conditions in both places are aligned.
> xc7series: fix condition detecting 2 empty frames between rows

- utils/segprint.py
Segprint proved very handy when working on tasks like #746
The spamming reported in #463 was annoying thought. This small fix addresses the problem.
> segprint: drop empty sections with -z -D

- docs/Makefile
@mithro Please merge if you think it's indeed wrong.
Also I'm not sure I see the point of the "Makefile" target but it might be just my lack of skill with Makefiles...
> docs: Rename wrong make target

- docs/architecture/interconnect.rst
- docs/architecture/reference.rst
- docs/format/db.rst
- docs/format/tile.rst
- docs/index.rst
Results can be found at https://mithro-prjxray.readthedocs.io/en/latest/
Fixes https://github.com/SymbiFlow/prjxray/issues/499
Need to clean up the database files section as segment stuff is probably wrong?
> Importing remaining wiki contents

- fuzzers/030-iob/Makefile
- fuzzers/030-iob/generate.py
This PR solves issue #820.
In #746 we have several bits missing, some of them belong to the IOB tiles.
Those bits were resolved correctly for Artix, hence it had to be analyzed why this doesn't happen for Zynq.
Turned out that alike Artix there seems to be a broken tile that has the bits which are being solved always on.
After this fix the IOB related bits are no longer unknown in the roi harness for zynq.
Also in this PR a small change in the pushdb target was introduced to avoid creating a segbits_liob.db in the database since there are no IOB on the left hand side in Zynq7.
> Resolve missing IOB bits for Zynq

- fuzzers/043-clk-rebuf-pips/Makefile
In #746  we are still missing few BUFG_REBUF PIPs calcualted in ``043-clk-rebuf-pips``.
To be precise these four PIPs are calculated for Artix, but are not for Zynq:
<pre>
CLK_BUFG_REBUF.CLK_BUFG_REBUF_R_CK_GCLK0_TOP.CLK_BUFG_REBUF_R_CK_GCLK0_BOT 27_13
CLK_BUFG_REBUF.CLK_BUFG_REBUF_R_CK_GCLK16_TOP.CLK_BUFG_REBUF_R_CK_GCLK16_BOT 27_12
CLK_BUFG_REBUF.CLK_BUFG_REBUF_R_CK_GCLK19_TOP.CLK_BUFG_REBUF_R_CK_GCLK19_BOT 27_60
CLK_BUFG_REBUF.CLK_BUFG_REBUF_R_CK_GCLK21_BOT.CLK_BUFG_REBUF_R_CK_GCLK21_TOP 27_94
</pre>
The dbfixup.py script removed these entries because they had 2 candidates while it was clear the features have only one bit.
Increasing the number of specimen in the fuzzer fixed this problem. The fuzzer is rather quick so there is no …
> Resolve missing CLK_REBUF PIPs bits for Zynq

- utils/cleandb.py
This PR adds a tool for removing partial DB from a global one. This is useful when a certain fuzzer is rerun during development
> utils: add cleandb tool

- prjxray/math_models.py
- prjxray/tile.py
- prjxray/timing.py
This is the beginning of the prjxray representation of the 7-series timing model.  This will form the basis for the 7-series route timing import.  Another PR will add a fuzzer to add the input values to the model.
I'm putting this PR up for review of the object model.
> Add objects and docstrings for timing model.

- fuzzers/056-pip-rem/generate.tcl
- fuzzers/Makefile
This PR is aimed at solving the instability problem with 056-pip-rem fuzzer reported in issue #661.
In brief:
The fuzzer fails with the following error:
<pre>
mynet_28: try 3                                                                 
PIP Tile: INT_L_X20Y94, LUT tile: INT_R_X3Y77                                   
LUT site: SLICE_X5Y77                                                           
route_via mynet_28 INT_L_X20Y94/LOGIC_OUTS_L3 INT_L_X20Y94/WW2BEG3              
Routing net mynet_28:                                                           
set route [find_routing_path -quiet -from CLBLM_R_X3Y77/CLBLM_L_A -to CLBLM_L_X20Y94/CLBLM_LOGIC_OUTS3]
CLBLM_R_X3Y77/CLBLM_L_A -> CLBLM_L_X20Y94/CLBLM_LOGIC_OUTS3: no route found …
> 056-pip-rem: Delete net and cell after unsuccessful routing attempt

- .github/kokoro/db-full.sh
- fuzzers/050-pip-seed/Makefile
- fuzzers/Makefile
It is possible for a PIP fuzzer to fail after reaching the defined iteration timeout due an incompatible piplist.
This happens when running all the fuzzers for one architecture and then running them for another architecture after just calling ``make clean`` in the ``fuzzers`` directory. The clean target doesn't clean the piplists which can cause problems during the execution of some pip fuzzers.
Namely, the ``todo`` file used in the pip fuzzer, which is generated based on the specific piplist generated for one architecture may not be compatible for another architecture which might not have the same pips.
The symptom is usually that the fuzzer which is set to finish within max 50 iterations, advances to a certain iteration, but later on performs all remaining iterations until 50 without …
> Add target to cleanup all piplists

- fuzzers/018-clb-ram/Makefile
In one of the CI runs for Artix7 (https://source.cloud.google.com/results/invocations/dac25fec-f8e0-43b4-bbf1-07b04e6cb593/targets/foss-fpga-tools%2Fprjxray%2Fpresubmit%2Fdatabase%2Fartix7/log)
I found the following conflict during db-check:
<pre>
00020594_089_23: had CLBLM_R_X11Y144.CLBLM_R.SLICEM_X0.WA8USED, got INT_R_X11Y144.INT_R.BYP_ALT4.GFAN0
</pre>
It turned out that the 018-bram fuzzer produces extra 20_23 bit for WA8USED - I could reproduce it locally.
Since the fuzzer runs very quickly (~1minute) I simply increased the specimen count. After this change I ran the fuzzer for 50 times and the result was correct.
> Fix bit collision caused by unstable 018-bram fuzzer

- fuzzers/007-timing/bel/Makefile
- fuzzers/007-timing/projects/placelut/generate.sh
- fuzzers/007-timing/projects/placelut_fb/generate.sh
- fuzzers/007-timing/projects/placelut_ff_fb/generate.sh
- fuzzers/007-timing/speed/Makefile
Added explicit call to python3 for all related scripts in fuzzer 007. This fixes making local builds when the system default Python is not set as Python3.
> Make build scripts of 007 explicitly use python3

- fuzzers/int_maketodo.py
- prjxray/util.py
- utils/checkdb.py
- utils/dbfixup.py
- utils/mergedb.py
- utils/mergedb.sh
- utils/parsedb.py
- utils/sort_db.py
Overview:
This PR implements a mechanism to track which fuzzer generated a specific solution described in #816.
Its main purpose is to track which fuzzer is responsible for solving the bits for a given feature.
This piece of information is very useful when debugging db-check failures.
Implementation:
The changes have been added to the mergedb (shell script and python script) which is called in every fuzzer by the pushdb target.
Functionality:
The fuzzer produces or updates additonal db files which apart from the bits for a particular feature also contain the information which fuzzer/fuzzers solved it. The files which are names ``segbits_*.origin_info.db`` are kept next to the regular ``segbits_*.db`` files.
An example with the …
> Generate db files with fuzzer name of origin

- fuzzers/053-pip-ctrlin/generate.tcl
- fuzzers/pip_loop.mk
This PR fixes #843
The origin of the problem is the same as in #838
There are two solution variants:
1. Move the solution of the CTRL*.GFAN01 bits from the 053-pip-ctrlin fuzzer to a new dedicated fuzzer (059-pip-ctrlin-gfan) (https://github.com/antmicro/prjxray/tree/prjxray_stabilization_053_pip_ctrlin_separation). Validated the solution by running both fuzzers for around 30 times without any timeout.
2. Implement the same solution as for #838. This is the preferred solution as it doesn't required adding a new fuzzer to the list.
> 053-pip-ctrlin: Fall back to todos bigger than specified number of lines

- lib/include/prjxray/xilinx/xc7series/configuration_bus.h
- lib/include/prjxray/xilinx/xc7series/configuration_column.h
- lib/include/prjxray/xilinx/xc7series/global_clock_region.h
- lib/include/prjxray/xilinx/xc7series/part.h
- lib/include/prjxray/xilinx/xc7series/row.h
yaml-lib defines convert as
```
template<T>
struct convert
```
Not as a ``class``.
> Correct class vs struct usage.

- fuzzers/058-pip-hclk/Makefile
- fuzzers/071-ppips/generate.tcl
These were no longer generated after 946892d1b and were removed from
prjxray-db at
https://github.com/SymbiFlow/prjxray-db/commit/b13ff7f8b368083c25be75bf6e2b4b9a6c21fd9d#diff-6a43cc2ab2e06b2a84b7effc16ca669e
> Add HCLK ppips.

- .github/kokoro/continuous-db-artix7.cfg
- .github/kokoro/continuous-db-kintex7.cfg
- .github/kokoro/continuous-db-zynq7.cfg
- .github/kokoro/db-full.sh
- .github/kokoro/kokoro-cfg.py
- .github/kokoro/presubmit-db-artix7.cfg
- .github/kokoro/presubmit-db-kintex7.cfg
- .github/kokoro/presubmit-db-zynq7.cfg
When analyzing the root cause of a failing fuzzer we just need its vivado logs.
Therefore there is no need to collect all of them.
What is missing though is often the contents of the build directory.
Collecting it for all fuzzers would kill the CI.
This PR implements the creation of an tgz archive with only the failing test cases.
> kokoro: Pack failing test cases instead of vivado logs

- utils/find_missing_segbits.py
This script allows to list PIPs which are missing segbits. It does not check any "non-pip" features.
The script operates on the prjxray files. It looks for all non-pseudo PIPs in each tile and then tries to find segbits for them. If a PIP is mared as non-pseudo in the `tile_type_*.json` file and is defined in `ppips_*.db` as "always" or "hint" then it is considered as pseudo.
A name pattern can be specified for tile types of interest and tile types of non-interest.
> An utility script that helps to find missing segbits

- fuzzers/050-pip-seed/generate.py
This PR solves issue #874 
The bits that were causing collisions in the fuzzer are now being solved in a separate fuzzer (051-pip-imuxlout-bypalts) and could be removed from the list of solved bits in 050-pip-seed.
The fix has been tested on the DNM branch (#848)
> 050-pip-seed: Don't solve BYP_ALT|IMUX.LOGIC_OUTS_ bits

- fuzzers/007-timing/bel/tim2json.py
> BEL fuzzer stabilization

- fuzzers/007-timing/bel/pin_alias_map.json
This PR is to add missing aliases to the `pin_alias_map.json`. The reason is that some timing definitions were missing in the bram sdf files because some pins/ports were skipped as the `tim2json.py` was not able to find the timing relative to those pins/ports
> 007-timing: added missing aliases for bram timing

- minitests/roi_harness/roi_base_div2.v
This cannot be used for an ROI harness until
https://github.com/SymbiFlow/prjxray/issues/891 is complete.
Command to build new harness
```
XRAY_ROIV=../roi_base_div2.v make
```
> Add ROI base file that adds a clock divider.

- fuzzers/int_generate.py
This PR fixes #895 
A detailed explanation of the problem can be found in the issue.
This PR modifies the script to keep the information whether the PIP is on the INT_L or INT_R tile up to the point where the ignoring mechanism comes in.
> Fix problem with falsely ignored PIPs

- minitests/srl/Makefile
- minitests/srl/README.md
- minitests/srl/par.tcl
- minitests/srl/srl32_init.v
- minitests/srl/srl32_x1.v
- minitests/srl/srl32_x1_and_lut6_x3.v
- minitests/srl/srl32_x2.v
- minitests/srl/srl32_x2_and_lut6_x2.v
- minitests/srl/srl32_x2_chain.v
- minitests/srl/srl32_x3.v
- minitests/srl/srl32_x3_and_lut6_x1.v
- minitests/srl/srl32_x3_chain.v
- minitests/srl/srl32_x4.v
- minitests/srl/srl32_x4_chain.v
- minitests/srl/syn.tcl
This PR adds several minitests for SRL32 (for now). Helps to identify which FASM features and in which combination are required to make SRLs work.
Each design can be built using Yosys+Vivado flow. After a build `bit2fasm` and `segprint` scripts are invoked.
> Minitests for SRLs

- fuzzers/036-iob-ologic/generate.py
DATA_RATE and DATA_RATE_OQ tags were generated from the same parameter which resulted in the solution being the same bit. This led to dbfixup rejecting the solution, hence the bits never made it to the final segbits.
> 036-iob-ologic: Solve bits for DATA_RATE_OQ

- fuzzers/035a-iob-idelay/Makefile
- utils/mergedb.sh
With this PR IDELAY bits solved for LIOI3 and RIOI3 tiles are pushed to the DB for:
- LIOI3_TBYTESRC
- LIOI3_TBYTETERM
- RIOI3_TBYTESRC
- RIOI3_TBYTETERM
> Pushing bits for IOI3 to the DB also for TBYTESRC and TBYTETERM tiles

- fuzzers/035-iob-ilogic/generate.py
- fuzzers/035-iob-ilogic/generate.tcl
- fuzzers/035-iob-ilogic/top.py
- Add non-decimal prefixes to feature parts
- Remove clocks in some samples to decouple ioi pips.
> ISERDES FASM feature improvements

- fuzzers/005-tilegrid/generate_full.py
Used the same mechanism as for IOBs.
For Litex this gives another 18 bits.
> Add alias for IOI3_SING tiles

- fuzzers/005-tilegrid/add_tdb.py
- fuzzers/005-tilegrid/hclk_ioi/Makefile
- fuzzers/030-iob/Makefile
- fuzzers/030-iob/generate.py
- fuzzers/030-iob/top.py
- fuzzers/030-iob/write_io_banks.tcl
- Also narrow HCLK_IOI tilegrid size to avoid coupling into [RL]IOI3.
Builds on #986
This solves remaining HCLK_IOI3 bits.
> Add stepdown feature to HCLK_IOI.

- utils/maskview.py
- utils/segview.py
This PR holds two useful utility scripts to be used for segbits files:
`maskview.py`
Shows bits read from single/multiple .db/.rdb files on a 2D plot (frame vs. bit). Can also show conflicts (same bit defined in multiple files). See docstring for more details.
`segview.py`
Shows bit patterns corresponding to tags in .db/.rdb files. Allows to visually determine feature groups etc. See docstring for more details.
> Segbits utils

- Makefile
- fuzzers/038-cfg/Makefile
- fuzzers/038-cfg/add_constant_bits.py
This PR is a remedy to the current situation in which 3 bits which are reported as unknown (#746) and thus show up in the fasm file keep the harness generation for Zynq from being successful and block the following PR: https://github.com/SymbiFlow/symbiflow-arch-defs/pull/500.
> fuzzers: 038-cfg: Add always on bit for Zynq

- Makefile
This commit fixes issue #1050 and most probably #1049 as well.
> Fix HARNESS_DIR path for db-extras-zynq7

- README.md
- requirements.txt
Updated the Quickstart Guide section of the README as some deviations were
required when following this with a fresh Ubuntu 16.04 install.  Fixes to
''requirements.txt'' were required to remove the "futures" dependency which is
in the python3 standard library and is only intended for use with python2;
"fasm" now goes by "pyfasm".
Signed-off-by: Jake Mercer <jmercer04@qub.ac.uk>
> README/Dependencies - Updated "Quickstart Guide"

- utils/sp6_bitstream_analyzer.py
This PR adds a Spartan 6 bitstream analyzer tool.
It has been used to create the tools from PR #1025. 
The script reads a Spartan6 bitstream and prints out some useful information.
It can also create a frames file with the configuration data words.
The bitstream is analyzed word by word and interpreted according to
the UG380 Configuration User Guide.
The tool can be used to derive the initialization, startup and finalization
sequence as well as the configuration data. The latter is written to a frames
file which can be used by the bitstream tools such as frames2bit to generate
a valid bitstream.
> utils: Add Spartan6 bitstream analyzer tool

- fuzzers/075-pins/generate.tcl
This is required to know which pin is a PUDC pin, which requires special
handling.
> Add pin functions column to package pins output.

- .gitmodules
- CMakeLists.txt
This PR adds sanitizers support to cmake - issue #1066 
Sanitizers can be enabled with SANITIZE_ADDRESS, SANITIZE_MEMORY, SANITIZE_THREAD or SANITIZE_UNDEFINED options for example by passing -DSANITIZE_ADDRESS=On to the command line.
To enable sanitizer support on a given target you have to add:
<pre>
add_executable(some_exe foo.c bar.c)
add_sanitizers(some_exe)
</pre>
This PR will have follow up PRs enabling sanitizer support for chosen targets.
> third_party: Add sanitizers-cmake module

- prjxray/tile_segbits_alias.py
This is required for emitting `[LR]IOI3_SING` frames in the ROI breakout.
> Enable ppips on aliased segbit files.

- lib/CMakeLists.txt
- lib/include/prjxray/xilinx/architectures.h
- lib/include/prjxray/xilinx/bitstream_reader.h
- lib/include/prjxray/xilinx/configuration.h
- lib/include/prjxray/xilinx/frames.h
- lib/xilinx/bitstream_writer.cc
- lib/xilinx/configuration.cc
- lib/xilinx/frames.cc
- tools/xc7frames2bit.cc
This PR adds initial support for the UltraScale+ devices to the bitstream tools.
The bitstream used for testing the tools was for Zynq UltraScale+ XCZU7EV-2FFVC1156 MPSoC which is featured on the ZCU104 evaluation kit (https://www.xilinx.com/products/boards-and-kits/zcu104.html).
The bitstream generated by the patcher and frames2bit tools were both successfully tested on hardware.
> Bitstream Tools: Add UltraScalePlus support

- Makefile
Added a check to the top-level Makefile to ensure that it has not been
invoked by ID 0 i.e. `root` or `sudo`.
Resolves #1100.
Signed-off-by: Jake Mercer <jake.mercer@civica.co.uk>
> MAKEFILE - Check if Root

- fuzzers/036-iob-ologic/generate.py
This PR fixes an issue in the 036-ologic fuzzer. The prefix of some of the OSERDES features was wrong.
> oserdese: fix wrong fasm prefix

- fuzzers/071-ppips/generate.tcl
Modified 071 to include PPIPs for:
- HCLK_IOI3
- HCLK_CMT
- CMT_TOP_L_UPPER_T, CMT_TOP_L_UPPER_B
- CMT_TOP_L_LOWER_T, CMT_TOP_L_LOWER_B
- CMT_TOP_R_UPPER_T, CMT_TOP_R_UPPER_B
- CMT_TOP_R_LOWER_T, CMT_TOP_R_LOWER_B
- INT_INTERFACE_L, INT_INTERFACE_R
- CLK_BUFG_REBUF
> Dump PPIPs for additional clock related tiles.

- fuzzers/001-part-yaml/Makefile
- fuzzers/001-part-yaml/add_iobanks.py
- fuzzers/001-part-yaml/generate.tcl
This PR adds the IO banks information to the part's json which is generate in the `001-part-yaml` fuzzer.
This information is needed for the xdc plugins (https://github.com/SymbiFlow/yosys-symbiflow-plugins/pull/1) to work and is a prerequisite for (https://github.com/SymbiFlow/symbiflow-arch-defs/pull/1158)
> 001-part-yaml: Add iobanks information to part's json

- minitests/iostandard/dump_iobs.tcl
- minitests/iostandard/features/Makefile
- minitests/iostandard/features/README.md
- minitests/iostandard/features/analyze.py
- minitests/iostandard/features/generate.py
- minitests/iostandard/features/snippets.py
- minitests/iostandard/syn+par.tcl
This is a minitest that allows to check which fasm features are enabled for which IO standard. It also allows to identify features that are active for unused IOBs when another IOB is active in the same bank. Moreover there is an utility script that automatizes translation of IOB verilog parameters to fasm features.
Signed-off-by: Maciej Kurc <mkurc@antmicro.com>
> Minitest for different IOSTANDARDs

- fuzzers/071-ppips/generate.tcl
Added dumping of PPIPs for Zynq PS7 tiles and interconnects. PPIPs related to MIO and DDR are omitted as they are not routable at all.
> Dumping PPIPs for Zynq PS7

- lib/xilinx/bitstream_writer.cc
- lib/xilinx/tests/xc7series/bitstream_writer_test.cc
This PR fixes bitstream header generation for series 7 and US+. Without this fix the bistreams could not be loaded from U-Boot or Linux on both Zynq-7000 and ZynqMP. The loading was failing on header check. The headers were fixed to follow the definitions from:
- Zynq7000: https://github.com/Xilinx/u-boot-xlnx/blob/master/drivers/fpga/zynqpl.c#L46
- ZynqMP: https://github.com/Xilinx/u-boot-xlnx/blob/master/drivers/fpga/zynqmppl.c#L18
Signed-off-by: Karol Gugala <kgugala@antmicro.com>
> bitstream_writer: fix 7 series and US+ headers

- fuzzers/run_fuzzer.py
The `run_fuzzers.py` script assumes that the memory reported by `free` is in GB, MB or kB.
This PR adds GiB, MiB and KiB support.
> fuzzers: Add support for KiB, MiB and GiB units

- database/Makefile
This PR is to correctly handle cleaning of part-dependent files in the new db structure after https://github.com/SymbiFlow/prjxray/pull/1196
> database make: clean also part-dependent directories

- fuzzers/run_fuzzer.py
Some versions of make using `--jobserver-fds` and some use `--jobserver-auth`, but they mean the same thing.  Handle parsing both.
See https://lists.gnu.org/archive/html/info-gnu/2016-05/msg00013.html
> Handle both jobserver-fds and jobserver-auth flags.

- Makefile
- fuzzers/074-dump_all/cleanup_site_pins.py
- fuzzers/074-dump_all/create_node_tree.py
- fuzzers/074-dump_all/generate_grid.py
- fuzzers/074-dump_all/reduce_site_types.py
- fuzzers/074-dump_all/reduce_tile_types.py
- requirements.txt
- utils/sort_db.py
- utils/xjson.py
Copy of #1226, remove use of xjson from `074`
>  - Rework how the `json` files are sorted (numbers are treated as numerics).
>  - Sort `csv` and `txt` files.
>  - Sort `segbits.*origin_info.db` files.
>  - Sort the grid file.
> 
> How this changes the output can be seen in https://github.com/SymbiFlow/prjxray-db/pull/11/files
> Fixing the sorting of database files

- Makefile
- requirements.txt
- utils/environment.python.sh
- utils/environment.sh
- utils/find_missing_segbits.py
These changes should change should fix all the warnings and make the current `make test-py` output from;
```
=================== 29 passed, 4 warnings in 1.65s ===================
```
to
```
=================== 29 passed, 0 warnings in 1.65s ===================
```
> Couple of small cleanup changes

- utils/segprint.py
Found this via trying to run `make install` in `minitests/picorv32-v`.
```
+ /home/tansell/github/SymbiFlow/prjxray/build/tools/bitread --part_file /home/tansell/github/SymbiFlow/prjxray/database/artix7/xc7a50tfgg484-1/part.yaml -F 0x00000000:0xffffffff -o design.bits -z -y design.bit
Bitstream size: 2298099 bytes
Config size: 574487 words
Number of configuration frames: 5408
DONE
++ fgrep CRITICAL vivado.log
+ test -z ''
+ python3 /home/tansell/github/SymbiFlow/prjxray/utils/segprint.py -z -D design.bits
Traceback (most recent call last):
File "/home/tansell/github/SymbiFlow/prjxray/utils/segprint.py", line 520, in <module>
main()
File "/home/tansell/github/SymbiFlow/prjxray/utils/segprint.py", line 516, in main
verbose=args.verbose)
File …
```
> Fix segprint tool for new tileconn.json location

- minitests/bram-sdp/Makefile
- minitests/bram-sdp/runme.sh
- minitests/bram-sdp/runme.tcl
- minitests/bram-sdp/top.v
This PR is to add a simple BRAMs minitest to verify feature relations among different RAMB18/36 packing locations.
> bram-sdp minitest: added minitest to check features of SDP brams

- fuzzers/005-tilegrid/generate.py
- fuzzers/005-tilegrid/generate_tiles.tcl
Prohibited sites are sites that Vivado will not place at.
> Add prohibited site list to tilegrid.

- prjxray/grid.py
- prjxray/grid_types.py
- tests/test_util.py
- utils/test_data/db/xc7/tilegrid.json
This PR adds the prohibited sites to the GridInfo
> grid: add prohibited sites to GridInfo

- fuzzers/030-iob/generate.py
Otherwise these bits were being lost (only having one IO type means the tile-wide tag is skipped by the solver), resulting in unknown bits with latest litedram.
> fuzzers: Add missing B-side IN_DIFF bits

- .gitattributes
GitHub uses https://github.com/github/linguist to do language stats.
linguist however mis-detects a bunch of things in this repo. It also
needs to be told about the "vendored" files in the repo.
This can be fixed by setting values via `.gitattributes` file which is
done here.
```
74.90%  Coq
13.42%  Python
3.71%   C++
3.62%   Tcl
1.42%   Makefile
1.26%   Verilog
0.73%   JavaScript
0.62%   Shell
0.10%   HTML
0.08%   XSLT
0.07%   CMake
0.03%   Assembly
0.02%   Ruby
0.01%   Dockerfile
```
```
42.45%  Python
25.18%  Verilog
12.00%  C++
10.96%  Tcl
4.07%   Makefile
2.34%   JavaScript
1.99%   Shell
0.34%   HTML
0.26%   XSLT
0.22%   CMake
0.09%   Assembly
0.08%   Ruby
0.03%   Dockerfile
```
> Add .gitattributes so GitHub gets the language right.

- .github/kokoro/db-full.sh
This PR fixes generation of `fails.tgz` tarballs with data from failed fuzzers.
> Fix kokoro tarball packing

- .gitignore
- setup.py
This PR adds a setup.py script to allow creation of prjxray package, usable in other projects.
> python: add setup.py to allow installing prjxray libraries

- fuzzers/030-iob/generate.py
- fuzzers/030-iob/process_rdb.py
- fuzzers/030-iob/top.py
- minitests/iostandard/dump_iobs.tcl
- minitests/iostandard/features/Makefile
- minitests/iostandard/features/generate.py
- minitests/iostandard/syn+par.tcl
- utils/fasm2frames.py
This PR adds SSTL15 features to fuzzer 030. No new bits were found for that IO standard. Some features changed names though.
Apart from that, the IOSTANDARD minitest has been updated to also check SSTL15 and set INTERNAL_VREF wherever appropriate. The latter change eliminated missing bits that the test was reporting previously.
> SSTL15 features

- settings/artix7_100t.sh
This PR adds a third IOI, LIOI_X0Y9, for special handling on the 100T.  Without this change,
LIOI_X0Y9 has empty "bits" in tilegrid.json.  Note there is no RIOI at Y9,
since the bottom right region of the 100T is high speed serial IO.
I wasn't really thinking; I just assumed each device would have two such IOIs that needed special handling.   But the 100T has three it seems: LIOI_X0Y9, LIOI3_X0Y109, RIOI3_X57Y109
Signed-off-by: Tim Callahan <tcal@google.com>
> Add a third IOI, LIOI_X0Y9, for special handling.  Without this change,

- setup.py
> setup.py: add fasm2frames as entry point instead of packaging utils

- utils/openocd/board-digilent-pynqz1.cfg
Signed-off-by: Andrew Butt <butta@seas.upenn.edu>
Usage example: openocd -f board-digilent-pynqz1.cfg -c "init; halt; pld load 0 top.bit; zynqpl_reset_release zynq.cpu0; halt; targets zynq.cpu0; load_image blink.elf; resume 0; exit" 
Loads the bitstream to the pl, releases the pl for interfacing with cpu0, and then loads the .elf file.  Currently this flashes over the FSBL bootloader because the blink.elf file I used is intended to run without a bootloader, but it should also be possible to upload with a bootloader with relatively few changes to the command.
> Add reset config to allow upload to PS region

- minitests/roi_harness/create_design_json.py
Signed-off-by: Andrew Butt <butta@seas.upenn.edu>
Allows a convergence of prjxray roi harnesses and a general partition region in https://github.com/SymbiFlow/symbiflow-arch-defs/pull/1561
> Add dedicated port type to harness design.json

- prjxray/overlay.py
- tests/test_util.py
Signed-off-by: Andrew Butt <butta@seas.upenn.edu>
Essentially an inverse roi.  Can accommodate cutting out multiple roi like regions.  Testing with symbiflow-arch-defs overlay generation and working.
> Add overlay.py to allow for overlay architecture generation

- Makefile
- fuzzers/032-cmt-pll/generate.py
- minitests/roi_harness/arty-common.sh
- minitests/roi_harness/basys3-common.sh
- settings/artix7.sh
- settings/artix7_50t.sh
This PR changes the main fuzzed device from A50T to A100T, which should result in new fuzzed bits.
The new bits should be related to additional device components, absent in A50T fabric.
Resolves https://github.com/SymbiFlow/prjxray/issues/1382
> Change main fuzzed device to A100T

- fuzzers/035b-iob-iserdes/generate.py
- utils/mergedb.py
I've messed up ISERDES feature names in https://github.com/SymbiFlow/prjxray/pull/978, they cannot begin (or contain only) a number as fasm assembler/disassembler does not allow that. This PR fixes that plus it adds a check to `mergedb.py` that prevents merging such features into the db in strict mode.
> ISERDES feature rename

- htmlgen/htmlgen.py
`get_setting` function is setup in `run` function and can't be used before it
Fixes #1413
Signed-off-by: Kamil Rakoczy <krakoczy@antmicro.com>
> Move setting output path to `run` function

- fuzzers/031-cmt-mmcm/generate.py
- fuzzers/031-cmt-mmcm/generate.tcl
This PR adds solution for some MMCM compensation settings. Adds the following features:
```
COMP.ZHOLD
COMP.Z_ZHOLD
```
The 2nd one contains the two missing bits required for the MMCM to run in hardware (when COMPENSATION = INTERNAL)
> MMCM compensation

- prjxray/node_model.py
The method `get_node_for_wire` fails in `node_model.py` when called for the first time and errors out with:
```
AttributeError: 'NoneType' object has no attribute 'items'
```
Example usage:
```
db = prjxray.db.Database(args.db_root, args.part)
node_model = db.node_model(progressbar_utils.progressbar)
test = node_model.get_node_for_wire('BRAM_L_X4Y0','BRAM_EE4B0_4')
```
This patch fixes the bug by calling `self._build_nodes()` when `self.nodes` is `None`. Moreover, the initialization of `self.wire_to_node_map` is changed to an empty dictionary, otherwise `assert tile_wire not in self.wire_to_node_map` fails with:
```
TypeError: argument of type 'NoneType' is not iterable
```
> Fixes get_node_for_wire by initializing self.node

- docs/Makefile
- docs/conf.py
- docs/requirements.txt
This PR fixes the missing symbolic links generation during building the Sphinx documentation
Resolves https://github.com/SymbiFlow/prjxray/issues/1504
https://github.com/SymbiFlow/prjxray/pull/1513 should be merged first.
> Fix links generation for markdown-code-symlinks

- fuzzers/005-tilegrid/Makefile
- fuzzers/005-tilegrid/add_tdb.py
- fuzzers/005-tilegrid/fuzzaddr/common.mk
- fuzzers/005-tilegrid/fuzzaddr/generate.py
- fuzzers/005-tilegrid/gtp_common/Makefile
- fuzzers/005-tilegrid/gtp_common/generate.tcl
- fuzzers/005-tilegrid/gtp_common/top.py
For the time being, the GTP_COMMON is restricted only to the artix7 devices. We can enable them for the other families in a second moment.
> gtp_common: add to tilegrid

- fuzzers/063-gtp-common-conf/Makefile
- fuzzers/063-gtp-common-conf/attrs.json
- fuzzers/063-gtp-common-conf/generate.py
- fuzzers/063-gtp-common-conf/generate.tcl
- fuzzers/063-gtp-common-conf/pushdb.sh
- fuzzers/063-gtp-common-conf/top.py
- fuzzers/Makefile
- prjxray/segmaker.py
- utils/mergedb.sh
This PR is based on top of https://github.com/SymbiFlow/prjxray/pull/1547 is still a WIP for the following reasons:
- requires some docstrings
- need to add support for the `IS_INVERTED` features.
The idea of this fuzzer is to have a json file containing a list of parameters of four kinds:
- *INT*: This is an integer parameter that requires X number of bits.
- *BIN*: This is a parameter with X numbers of required bits
Given that the GTP common does not have any string parameter, the above parameter types are the only ones.
The json file contains also an `encoding` field, which, as far as I have understood, should be interpreted as the binary representation of the value assigned, and this is relevant mostly for the *INT* parameter type.
E.g.:
The `PLL0_REFCLK_DIV` parameter has two …
> gtp_common: add conf fuzzer

- minitests/get_unknown_bits_count.sh
This is a small script to help getting the number of missing bits for many different minitests.
Example output:
```
$ ./get_unknown_bits_count.sh -m hamsternz-displayport litex/nexys_video_sata
-----------------------------
hamsternz-displayport
-----------------------------
Total of unknown bits: 53
Total of unknown frames: 9
-----------------------------
litex/nexys_video_sata
-----------------------------
Total of unknown bits: 17
Total of unknown frames: 7
```
> minitest: add utility script to get unknown bits

- prjxray/fasm_disassembler.py
To get a better understanding on the differing unknown bits from two different bitstreams it is helpful to have all the missing ones sorted.
It happens that, two bitstreams that have many unknown bits and differ only in one of these unkown bits, have a completely unsorted output when using the `--verbose` option, making it hard to track where the differences are.
> disassembler: sort remaining unknown bits

- fuzzers/064-gtp-channel-conf/pushdb.sh
- fuzzers/065-gtp-common-pips/Makefile
- fuzzers/065-gtp-common-pips/generate.py
- fuzzers/065-gtp-common-pips/generate.tcl
- fuzzers/065-gtp-common-pips/gtp_common_pip_list.tcl
- fuzzers/065-gtp-common-pips/output_cmt.tcl
- fuzzers/065-gtp-common-pips/top.py
- fuzzers/Makefile
- fuzzers/int_loop.sh
- fuzzers/pip_loop.mk
- prjxray/segmaker.py
- utils/mergedb.sh
This fuzzer is to get the clock-related PIPs corresponding to the `GTP_COMMON_MID_[LEFT|RIGHT]` tile that are used to route signals from the possible following sources:
- `GTP_CHANNEL` RX and TX output clocks
- `IBUFDS_GTE2` Output clock
- Clocks from other Clock Region's sources (e.g. PLL, MMCM, etc.)
The fuzzer requires some fixes, hence the WIP in the title. In fact, it seems that, out of the 168 PIPs, ~30 of them keep having zero candidates, even after many specimens have been generated.
It seems that there are two set bits for each PIP, hence the `-c 2` parameter to segmatch.
There is also to handle the fact that this fuzzer should not run for artix 50T and 100T, as they have no `GTP_COMMON_MID_[LEFT|RIGHT]` tiles. I believe …
> 065-gtp-common-pips: add fuzzer to document GTP_COMMON_MID pips

- fuzzers/005-tilegrid/Makefile
- fuzzers/005-tilegrid/add_tdb.py
- fuzzers/005-tilegrid/generate_full.py
- fuzzers/005-tilegrid/gtp_int_interface/Makefile
- fuzzers/005-tilegrid/gtp_int_interface/generate.tcl
- fuzzers/005-tilegrid/gtp_int_interface/top.py
The GTP_INT_INTERFACE has `DELAY` PIPs which can be triggered only by using `route_via` or, if the router needs to solve hold violations. 
Given that producing hold violations is non-trivial, the route_via option was selected.
Moreover, one port of the GTP_COMMON site has been selected (`PLL0LOCKEN`), as it seems to produce stable results among specimens. Given that the traversed GTP_INT_INTERFACE is in the middle of the column, its baseaddress, offset and word counts has to be propagated in the `generate_full` script, which takes into account of the HCLK tile to add an additional 1-word offset.
> 005-tilegrid: add gtp_int_interface tile baseaddress

- fuzzers/063-gtp-common-conf/README.md
- fuzzers/063-gtp-common-conf/generate.py
- fuzzers/063-gtp-common-conf/top.py
This changes allow to document features that appearr when the GTREFCLK ports of the GTP_COMMON are connected to the IBUFDS_GTE2 sites' outputs.
> 063-gtp-common-conf: get features corresponding to IBUFDS -> GTP

- fuzzers/065-gtp-common-pips/Makefile
This PR increases the specimen count from 60 to 100 for the 065-gtp-common-pips. This because it appears to be harder to get PIPs in following iterations. With this change, the fuzzer takes only one iteration to finish, while, with 60 specimens per iteration, the fuzzer took a total of 4 iterations (at least locally).
> 065-gtp-common-pips: increase specimens count

- fuzzers/065-gtp-common-pips/Makefile
- fuzzers/065-gtp-common-pips/generate.py
- fuzzers/065-gtp-common-pips/generate.tcl
- fuzzers/065-gtp-common-pips/gtp_common_pip_list.tcl
- fuzzers/065-gtp-common-pips/top.py
- fuzzers/065b-gtp-common-pips/Makefile
- fuzzers/065b-gtp-common-pips/generate.py
- fuzzers/065b-gtp-common-pips/generate.tcl
- fuzzers/065b-gtp-common-pips/gtp_common_pip_list.tcl
- fuzzers/065b-gtp-common-pips/output_cmt.tcl
- fuzzers/065b-gtp-common-pips/top.py
- fuzzers/Makefile
This PR splits the 065-gtp-common-pips fuzzer in two, due to a difference in the number of bits for the PIPs, the TODO lists that needed to be generated, as well as the piplist.
The GTP_COMMON pips can be divided in two categories:
- PIPs connecting GTP_CHANNEL and IBUFDS_GTE2 wires to the clock spine
- PIPs connecting clock wires from the CMT
The second kind of PIPs has three bits, which are missed with the previous version of the fuzzer.
> Fix 065 gtp common pips

- fuzzers/063-gtp-common-conf/generate.py
- fuzzers/063-gtp-common-conf/generate.tcl
- fuzzers/063-gtp-common-conf/top.py
This PR enables a feature that is triggered on specific connectivity of the DRP (Dynamic Reconfiguration Port) port in the GTP_CHANNEL primitives.
Basically, this feature should enable the DRP for all of the tiles in the column, as the bits appear in the words belonging to the GTP_COMMON tile.
It is enough to have one only GTP_CHANNEL primitive with all the required DRP ports connected accordingly, to enable this feature.
> 063-gtp-common-conf: add DRP_ENABLE feature

- fuzzers/065-gtp-common-pips/gtp_common_pip_list.tcl
- fuzzers/065b-gtp-common-pips/gtp_common_pip_list.tcl
This fixes an issue discovered in [this master CI build](https://source.cloud.google.com/results/invocations/7379c769-f46e-440a-8777-8d34c075860e).
065- and 065b-gtp-common-pips share the piplist directory and the vivado project needs to be located in separate directories.
> 065-gtp-common-pips: fix overlapping piplist project names

- fuzzers/030-iob/Makefile
- fuzzers/030-iob/top.py
This PR lets choose a different I/O settings for each bank instead of each specimen. This way we need less specimens.
Given that there are quite some I/O settings missing, this enhancement is required to keep the number of specimens low also for when other settings will be added.
> 030-iob: increase fuzzer efficiency

- fuzzers/101-dsp-pips/Makefile
- fuzzers/101-dsp-pips/dsp_pip_list.tcl
- fuzzers/101-dsp-pips/generate.py
- fuzzers/101-dsp-pips/generate.tcl
- fuzzers/101-dsp-pips/ports.py
- fuzzers/101-dsp-pips/top.py
- fuzzers/Makefile
The DSP tiles have `TIEOFF` sites which can be used instead of the INT `TIEOFF`s. These "internal" `TIEOFF`s add some extra PIPs for some of the DSP inputs.
This fuzzer documents these GND and VCC PIPs.
> 101-dsp-pips: solve DSP-related PIPs

- fuzzers/005-tilegrid/add_tdb.py
Changing max frames for GTP_COMMON from 42 to 32. This was causing a huge cascading errors while running fasm2frames, resulting in a bugged frames file.
> 005-tilegrid: fix GTP common frames

- fuzzers/005-tilegrid/add_tdb.py
- fuzzers/005-tilegrid/generate_full.py
- fuzzers/005-tilegrid/util.py
This PR adds automatic frames count extraction from the `part.json` of a given part to the `005-tilegrid` fuzzer.
Porting this solution form U-Ray was mentioned in PR #1603
When the specified frames count value exceeds the maximum allowed value a warning is displayed and the value falls back to the maximum allowed.
> 005-tilegrid: Extract frames count information from part's json

- .github/kokoro/db-full.sh
- .github/kokoro/db-quick.sh
- .github/kokoro/steps/hostcheck.sh
Validated with a check if `/tmpfs2` is mounted:
```
========================================
Check storage
----------------------------------------
++ mount
++ grep /tmpfs2
++ MOUNT_RET=1
++ set +x -e
----------------------------------------
Error: No storage is mounted on /tmpfs.
----------------------------------------
========================================
Dmesg dump
----------------------------------------
[    0.000000] Initializing cgroup subsys cpuset
[    0.000000] Initializing cgroup subsys cpu
[    0.000000] Initializing cgroup subsys cpuacct
```
> Add kokoro hostcheck

- fuzzers/061-pcie-conf/Makefile
- fuzzers/061-pcie-conf/generate.py
- fuzzers/061-pcie-conf/generate_ports.tcl
- fuzzers/061-pcie-conf/params.py
- fuzzers/061-pcie-conf/top.py
There are several changes introduced in this PR:
* Unification of the parameters used in the fuzzer. Parameters were translated to the JSON format (the same as in GTP fuzzers)
* Added generate_port script used to export JSON file with ports definitions of the PCIE_2_1 site
* Added exporting ports and attributes JSON files to prxjray-db
Depends on `make_ports.py` tool introduced in: https://github.com/SymbiFlow/prjxray/pull/1614
> Rework pcie-conf fuzzer

- fuzzers/030-iob/Makefile
Should fix an instability for the zynq part.
> 030-iob: increase number of specimens

- fuzzers/071-ppips/generate.tcl
The current `ppips_dsp_[lr].db` are empty and should contain information required for routing DSPs. An example of a generated `ppips_dsp_l.db` is attached to this PR for the zynq7010.
[ppips_dsp_l.db.zip](https://github.com/SymbiFlow/prjxray/files/6394677/ppips_dsp_l.db.zip)
Signed-off-by: Ian Taras <itaras@isi.edu>
> Fuzzer-071 Generates ppips for DSP

- fuzzers/034-cmt-pll-pips/fixup_and_group.py
(edit) Fixes bits which were not filtered out for the `CMT_TOP_R` case.
> 034-cmt: fix conflicting PIPs

- .github/kokoro/continuous-db-kintex7.cfg
- .github/kokoro/presubmit-db-kintex7.cfg
- .github/kokoro/steps/hostsetup.sh
- .github/kokoro/steps/xilinx.sh
Enables generation of database for larger Kintex parts.
Signed-off-by: Tim 'mithro' Ansell <tansell@google.com>
> Adding connection to a Xilinx license server.

- .github/kokoro/steps/hostsetup.sh
- .github/workflows/ci.yml
- .github/workflows/scripts/db.sh
- .github/workflows/scripts/hostinfo.sh
- Makefile
- fuzzers/065-gtp-common-pips/Makefile
- fuzzers/065b-gtp-common-pips/Makefile
- fuzzers/072-ordered_wires/Makefile
- fuzzers/073-get_counts/Makefile
- fuzzers/074-dump_all/Makefile
- fuzzers/075-pins/Makefile
- fuzzers/Makefile
- fuzzers/run_fuzzer.py
- prjxray/tile_segbits.py
- prjxray/util.py
- requirements.txt
- utils/roi_all.py
This PR is to start transitioning towards GH custom runners for CI 
> gh: initial use of gh action custom runners

- .github/workflows/database.yml
- .github/workflows/tests.yml
- utils/dbfixup.py
- utils/sort_db.py
There seem to be yet another race condition that causes an [intermittent failure](https://github.com/f4pga/prjxray/runs/5489565933?check_suite_focus=true):
```
- 2h40m: Traceback (most recent call last):
- 2h40m:   File "/root/prjxray/prjxray/utils/bit2fasm.py", line 126, in <module>
- 2h40m:     main()
- 2h40m:   File "/root/prjxray/prjxray/utils/bit2fasm.py", line 122, in main
- 2h40m:     args.canonical)
- 2h40m:   File "/root/prjxray/prjxray/utils/bit2fasm.py", line 50, in bits_to_fasm
- 2h40m:     sort_key=grid.tile_key,
- 2h40m:   File "/root/prjxray/prjxray/third_party/fasm/fasm/output.py", line 386, in merge_and_sort
- 2h40m:     for line in model:
- 2h40m:   File "/root/prjxray/prjxray/prjxray/fasm_disassembler.py", line 131, in find_features_in_bitstream
- 2h40m: …
```
> Fix race condition

- utils/environment.sh
For everyday use, it is common to use a personal wrapper setenv script that both sets Vivado license environment, and that sources the usual vivado settings64.sh.
If by mistake such wrapper is set in XRAY_VIVADO env var instead of the required settings.sh, then weird things can happen to the prompt when utils/environment.sh is sourced.
This PR is really simple : just protect source of $XRAY_VIVADO with quotes.
> Protect against unintentionally wrongly set env var XRAY_VIVADO

- .github/workflows/Automerge.yml
- .github/workflows/Pipeline.yml
- .github/workflows/scripts/db.sh
- .github/workflows/scripts/xilinx.sh
> Setup connection to Xilinx license server.

- fuzzers/030-iob18/Makefile
- fuzzers/030-iob18/generate.py
- fuzzers/030-iob18/top.py
- fuzzers/030-iob18/write_io_banks.tcl
- utils/bit2fasm.py
Signed-off-by: Hans Baier <hansfbaier@gmail.com>
> various fixes for 030-iob18

- fuzzers/035a-iob18-odelay/Makefile
- fuzzers/035a-iob18-odelay/generate.py
- fuzzers/035a-iob18-odelay/generate.tcl
- fuzzers/035a-iob18-odelay/top.py
- fuzzers/Makefile
- prjxray/segmaker.py
Hi, I have been successfully running the LiteX K7DDRPHY with the results of this fuzzer,
see this thread:
https://twitter.com/hansfbaier/status/1617651908453494785
> Kintex7 ODELAYE2 fuzzer

- CMakeLists.txt
This is an alternative to #2117.  Instead of compiling dependencies (abseil) with c++14, this PR removes this repo's c++14 directive.
> Remove c++14 directive

- tools/bits2rbt/header.h
I got some issues compiling prjxray under gcc 13.1.1.
In order to mitigate this, I have added the missing import to tools/bits2rbt/header.h.
```
In file included from /home/dennis/tmp/prjxray/tools/bits2rbt/header.cc:1:
/home/dennis/tmp/prjxray/tools/bits2rbt/header.h:11:28: error: ‘uint32_t’ was not declared in this scope
11 |                std::vector<uint32_t>& fpga_config_packets);
|                            ^~~~~~~~
/home/dennis/tmp/prjxray/tools/bits2rbt/header.h:7:1: note: ‘uint32_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
6 | #include <vector>
+++ |+#include <cstdint>
7 | 
/home/dennis/tmp/prjxray/tools/bits2rbt/header.h:11:36: error: template argument 1 is invalid
11 |                std::vector<uint32_t>& fpga_config_packets);
| …
```
> Add missing import for cstdint to tools/bits2rbt/header.h

- fuzzers/038-cfg-startup/Makefile
- fuzzers/038-cfg-startup/generate.py
- fuzzers/038-cfg-startup/generate.tcl
- fuzzers/038-cfg-startup/top.py
- fuzzers/071-ppips/generate.tcl
- fuzzers/Makefile
This contains a fuzzer for bits that only show up, when USRCCLKO is connected to
a non-constant net.
Also it turned out that the switchboxes on the CFG_CENTER tiles are all pseudo.
I have been able to get a working BSCANE2 with those,
and also a working STARTUPE2 test.
Since the other primitives are not that much different qualitatively,
I reckon most CFG_CENTER primitives should work with this.
> Fuzzer for STARTUPE2, ppips for CFG_CENTER_TOP/MID/BOT

- prjxray/fasm_assembler.py
I have an issue in the Spartan7 db, where there seem to appear invalid word addresses.
Sample output of this patch:
```
invalid word address 101 in feature: IOI_ILOGIC0_CLK.IOI_LEAF_GCLK0 line: LIOI3_SING_X0Y149.IOI_ILOGIC0_CLK.IOI_LEAF_GCLK0
invalid word address 101 in feature: IOI_ILOGIC0_CLK.IOI_LEAF_GCLK0 line: LIOI3_SING_X0Y149.IOI_ILOGIC0_CLK.IOI_LEAF_GCLK0
invalid word address 101 in feature: IOI_ILOGIC0_CLK.IOI_LEAF_GCLK0 line: LIOI3_SING_X0Y149.IOI_ILOGIC0_CLK.IOI_LEAF_GCLK0
invalid word address 101 in feature: IOI_ILOGIC0_CLKB.IOI_LEAF_GCLK0 line: LIOI3_SING_X0Y149.IOI_ILOGIC0_CLKB.IOI_LEAF_GCLK0
invalid word address 101 in feature: IOI_ILOGIC0_CLKB.IOI_LEAF_GCLK0 line: LIOI3_SING_X0Y149.IOI_ILOGIC0_CLKB.IOI_LEAF_GCLK0
invalid word address 101 in feature: …
```
> print a human readable warning when encountering invalid word addresses

- fuzzers/036-iob-ologic/generate.py
- fuzzers/036-iob-ologic/generate.tcl
- fuzzers/036-iob-ologic/top.py
This enables master/slave support, because that is what those datawidths are for.
> 036-iob-ologic: Also fuzz DATA_WIDTH 10 and 14
