f4pga/prjxray

- README.md
- download-latest-db.sh
> Make download-latest-db use https by default.

- fuzzers/005-tilegrid/README.txt
- fuzzers/005-tilegrid/generate.tcl
- fuzzers/005-tilegrid/top.v
> tilegrid fuzzer: document better

- README.md
- fuzzers/012-clbn5ffmux/generate.sh
- fuzzers/015-clbnffmux/generate.sh
- fuzzers/016-clbnoutmux/generate.sh
> Document MUXF8 Vivado compatibility issue

- fuzzers/070-tileconn/generate.py
- fuzzers/070-tileconn/generate.tcl
Fixes #25 
Signed-off-by: Clifford Wolf <clifford@clifford.at>
> Replace 070-tileconn with a new (hopefully strictly better) implementation

- fuzzers/070-tileconn/generate.py
- utils/tileconnwire.py
Signed-off-by: Clifford Wolf <clifford@clifford.at>
> Add tileconnwire.py utils script

- README.md
- fuzzers/Makefile
Signed-off-by: Clifford Wolf <clifford@clifford.at>
> Fixes in fuzzers top-level Makefile, Update README

- minitests/bram/Makefile
> bram minitest: fix broken makefile

- .travis.yml
Signed-off-by: Rick Altherr <kc8apf@kc8apf.net>
> Travis config that builds C++ tools

- lib/CMakeLists.txt
- lib/include/prjxray/xilinx/xc7series/bitstream_writer.h
- lib/xilinx/xc7series/bitstream_writer.cc
- lib/xilinx/xc7series/bitstream_writer_test.cc
Note: this needs some cleanup / review in at least the following areas:
-General formatting. I couldn't get make format to do anything (although it does run)
-type 0 packet handling: maybe we should put something in ConfigurationPacket to make this easier to add them? If we don't want InitWithWords to make a type 0 packet, maybe something like ConfigurationPacket::type0 static member, a function, or something of that sort
> Bitstream writer utility class

- tools/simpleroute.py
Signed-off-by: Clifford Wolf <clifford@clifford.at>
> Add simpleroute.py tool for routing signals through ROI

- minitests/roi_harness/basys3.sh
> basys3.sh: use proper script to setup environment

- minitests/partial_reconfig_flow/README.md
> partial_config_flow: fix readme bad commands

- lib/CMakeLists.txt
- lib/include/prjxray/xilinx/xc7series/crc.h
- lib/include/prjxray/xilinx/xc7series/ecc.h
- lib/xilinx/xc7series/crc_test.cc
- lib/xilinx/xc7series/ecc_test.cc
Signed-off-by: Herbert Poetzl <herbert@13thfloor.at>
> Added ICAP CRC and ECC calculations and tests

- docs/architecture/overview.rst
Signed-off-by: Rick Altherr <kc8apf@kc8apf.net>
> docs: Fix poor grammar

- docs/Makefile
- docs/architecture/bitstream_format.rst
- docs/architecture/configuration.rst
- docs/architecture/glossary.rst
- docs/index.rst
- requirements.txt
Description of how configuration frame addressing relates to physical chip design.  Rough notes on frame data loading process and packet format used to run the state machine used.
> docs: low-level configuration details

- .gcloudignore
- .gitignore
- Dockerfile
- Makefile
- cloudbuild.yaml
- database/Makefile
- database/Makefile.database
Dockerfile and Container Builder configurations to build a database from scratch and package the resulting database in a ready-to-serve nginx-based Docker image.
> Docker-based db builder

- fuzzers/019-ndi1mux/Makefile
Per https://github.com/SymbiFlow/prjxray/issues/86
> ndi1mux: dont add to slicel

- fuzzers/005-tilegrid/README.md
- fuzzers/011-ffconfig/README.md
- fuzzers/018-clbram/README.md
- minitests/clb_muxf8/README.md
- minitests/roi_harness/README.md
Fixed Bullet Point Lists in README.md files
> Fixed Bullet Point Lists in README.md files

- docs/database development process/overview.rst
- docs/db_dev_process/overview.rst
- docs/index.rst
Signed-off-by: Davide <davide.toldo@stud.tu-darmstadt.de>
> Added database development process to FAQ

- README.md
by putting it into the main README file
> Added link to make ReadTheDocs documentation easier to find

- Dockerfile
> Dockerfile: Run make with output syncing an more warnings.

- .github/autolabeler.yml
> infra: Adding autolabeler configuration.

- docs/architecture/glossary.rst
- docs/architecture/overview.rst
Added terms from wiki (https://github.com/SymbiFlow/prjxray/wiki/Glossary) and cleaned up some words.
Signed-off-by: Sarah Maddox <sarahmaddox@google.com>
> Merged terms from wiki glossary

- CONTRIBUTING.md
- README.md
Updated the README file, then ran ./.update-contributing.py to update CONTRIBUTING.md. The Python program picked up a couple more changes from someone else's prior commit to the README, and added them to CONTRIBUTING.MD as well as mine.
Signed-off-by: Sarah Maddox <sarahmaddox@google.com>
> Added info on signoff via commit statement.

- CONTRIBUTING.md
- README.md
- UPDATING-THE-DOCS.md
- docs/architecture/configuration.rst
Signed-off-by: Sarah Maddox <sarahmaddox@google.com>
> Adds a guide to updating the Project X-Ray docs

- docs/format/tile.rst
- docs/index.rst
> docs: tileconn, tilegrid

- fuzzers/007-timing/csv_group2flat.py
- fuzzers/007-timing/projects/corner.mk
- fuzzers/007-timing/projects/project.mk
- fuzzers/007-timing/timfuz.py
- fuzzers/007-timing/timfuz_massage.py
- fuzzers/007-timing/timfuz_solve.py
Selectable build dir
Bug fix: min corner may drop group
Remove duplicate / old equation massage code
Add some documentation
Corner makefile fix (target builds timgrid-vc.json, not timgrid-s.json)
Add QoR output to all corner builds
> timfuz: misc cleanup

- minitests/roi_harness/.gitignore
- minitests/roi_harness/Makefile
- minitests/roi_harness/defines.v
- minitests/roi_harness/runme.sh
- minitests/roi_harness/runme.tcl
For https://github.com/SymbiFlow/prjxray/issues/128
We could make this more flexible, but I think this is good enough. This code should become obsolete anyway once we are more established
> roi_harness: small project option

- prjxray/db.py
- prjxray/grid.py
- prjxray/lib.py
- prjxray/tile.py
- Add caching to db.py for tile types
- Add wire info to tile types to allow easy pip/site access from wire names
> Additional library behaviors after integration.

- fuzzers/005-tilegrid/generate.py
- utils/segmaker.py
Improve segmaker documentation, organization, and add some sanity checks.
> Segmaker debug

- .gitignore
- Makefile
- fuzzers/074-dump_all/generate_after_dump.sh
- prjxray/lib.py
* `074-dump_all` - Don't fail if output dir doesn't exist.
* Add Python virtualenv to make it easier to install all the Python requirements.
> Changes from trying to generate updated database

- requirements.txt
The timing fuzzer requires;
* numpy
* scipy
* sympy
> Adding timing fuzzer needs to requirements.txt

- lib/xilinx/xc7series/part.cc
Signed-off-by: Michael Gielda <mgielda@antmicro.com>
> lib: xilinx: catch exceptions by reference

- fuzzers/011-ffconfig/generate.py
- fuzzers/012-clbn5ffmux/generate.py
- fuzzers/013-clbncy0/generate.py
- fuzzers/014-ffsrcemux/generate.py
- fuzzers/015-clbnffmux/generate.py
- fuzzers/016-clbnoutmux/generate.py
- fuzzers/017-clbprecyinit/generate.py
- fuzzers/018-clbram/generate.py
- fuzzers/019-ndi1mux/generate.py
- fuzzers/050-intpips/generate.py
- fuzzers/051-imuxlout/generate.py
- fuzzers/052-clkin/generate.py
- fuzzers/053-ctrlin/generate.py
- fuzzers/054-gfan/generate.py
- fuzzers/055-gnd/generate.py
- fuzzers/056-rempips/generate.py
- fuzzers/057-bipips/generate.py
- fuzzers/058-hclkpips/generate.py
- fuzzers/100-dsp-mskpat/generate.py
This was suppose to be in https://github.com/SymbiFlow/prjxray/pull/159, but only lutinit was updated.
> fuzzers: fix addtag regression

- experiments/clbpips/generate.py
- experiments/gndvcc/generate.py
- experiments/pipsroute/generate.py
- fuzzers/010-lutinit/generate.py
- fuzzers/011-ffconfig/generate.py
- fuzzers/012-clbn5ffmux/generate.py
- fuzzers/013-clbncy0/generate.py
- fuzzers/014-ffsrcemux/generate.py
- fuzzers/015-clbnffmux/generate.py
- fuzzers/016-clbnoutmux/generate.py
- fuzzers/017-clbprecyinit/generate.py
- fuzzers/018-clbram/generate.py
- fuzzers/019-ndi1mux/generate.py
- fuzzers/050-intpips/generate.py
- fuzzers/051-imuxlout/generate.py
- fuzzers/052-clkin/generate.py
- fuzzers/053-ctrlin/generate.py
- fuzzers/054-gfan/generate.py
- fuzzers/055-gnd/generate.py
- fuzzers/056-rempips/generate.py
- fuzzers/057-bipips/generate.py
- fuzzers/058-hclkpips/generate.py
- fuzzers/100-dsp-mskpat/generate.py
- prjxray/segmaker.py
> segmaker.py: move to prjxray, class segmaker => Segmaker

- fuzzers/018-clbram/top.py
- prjxray/util.py
> 018-clbram: query SLICEM instead of guessing

- fuzzers/018-clbram/top.py
- fuzzers/019-ndi1mux/top.py
> 019-ndi1mux: query SLICEM instead of guessing

- fuzzers/011-ffconfig/top.py
- fuzzers/012-clbn5ffmux/top.py
- fuzzers/013-clbncy0/top.py
- fuzzers/014-ffsrcemux/top.py
- fuzzers/015-clbnffmux/top.py
- fuzzers/016-clbnoutmux/top.py
See https://github.com/SymbiFlow/prjxray/issues/157
Fixes most of them. I tried to quickly fix 017-clbprecyinit, but its a little more complicated and my quick fix didn't work. Its not actually broken though. Revisit if we run into issues and/or I get bored
> Gen sites cleanup

- fuzzers/051-imuxlout/generate.py
- fuzzers/052-clkin/generate.py
- fuzzers/053-ctrlin/generate.py
- fuzzers/057-bipips/generate.py
- prjxray/segmaker.py
Fixes: https://github.com/SymbiFlow/prjxray/issues/165
> Allow empty segement generation on select fuzzers that loop

- fuzzers/014-ffsrcemux/top.py
> Fix indirection.

- fuzzers/011-ffconfig/top.py
- fuzzers/012-clbn5ffmux/top.py
- fuzzers/013-clbncy0/top.py
- fuzzers/014-ffsrcemux/top.py
- fuzzers/015-clbnffmux/top.py
- fuzzers/016-clbnoutmux/top.py
- fuzzers/017-clbprecyinit/top.py
- fuzzers/018-clbram/top.py
- fuzzers/019-ndi1mux/top.py
> fuzzers: replace inline verilog with top_harnesS()

- utils/blockwidth.py
- utils/environment.sh
This fixes https://github.com/SymbiFlow/prjxray/issues/176 , or at least shows its basic idea. Suggest filing a separate issue if we want to formally integrate into tilegrid
> blockwidth: tool to print minor address groups

- utils/blockwidth.py
> blockwidth: shrink minor address print

- minitests/roi_harness/Makefile
- minitests/roi_harness/arty.sh
Allows generating the fuzzers/001-part-yaml for the Arty part.
> minitests/roi_harness: Add XRAY_PIN values valid for Arty.

- database/artix7/settings.sh
fixes https://github.com/SymbiFlow/prjxray/issues/201
> Artix 7: remove duplicate ROI

- fuzzers/101-bram-config/generate.py
- fuzzers/101-bram-config/top.py
- minitests/bram_basic/Makefile
- minitests/bram_basic/top.v
> bram-config: WRITE_MODE

- docs/architecture/dram_configuration.rst
> Add documentation for DRAM segbits.

- prjxray/db.py
- utils/segprint.py
Use prjxray.db lib. Flatten grid data structure
> Segprint cleanup

- fuzzers/019-ndi1mux/generate.py
> Rename DI1MUX to be underneith the *LUT.

- minitests/roi_harness/runme.sh
- minitests/roi_harness/runme.tcl
> Add UART port to ROI harness.

- utils/segprint.py
Fixes https://github.com/SymbiFlow/prjxray/issues/218
> Segprint: print related tiles

- fuzzers/025-bram-config/Makefile
- fuzzers/026-bram-data/Makefile
fixes https://github.com/SymbiFlow/prjxray/issues/227
> bram: make run targets

- fuzzers/clb.mk
- utils/dbfixup.py
For https://github.com/SymbiFlow/prjxray/issues/239
> clb.mk: fix bad pushdb file name

- fuzzers/025-bram-config/Makefile
- fuzzers/050-intpips/Makefile
- fuzzers/051-imuxlout/Makefile
- fuzzers/052-clkin/Makefile
- fuzzers/053-ctrlin/Makefile
- fuzzers/054-gfan/Makefile
- fuzzers/055-gnd/Makefile
- fuzzers/056-rempips/Makefile
- fuzzers/057-bipips/Makefile
- fuzzers/058-hclkpips/Makefile
- fuzzers/100-dsp-mskpat/Makefile
- fuzzers/clb.mk
- prjxray/util.py
- utils/bits2fasm.py
- utils/fasm2frames.py
- utils/fasm2pips.py
- utils/fasm_pprint.py
- utils/quick_test.py
- utils/verify_tile_connections.py
Fixes https://github.com/SymbiFlow/prjxray/issues/233
> --db_root => --db-root

- database/Makefile
fixes https://github.com/SymbiFlow/prjxray/issues/189
> database: make clean

- prjxray/util.py
- utils/dbfixup.py
- utils/environment.sh
- utils/mergedb.sh
- utils/parsedb.py
Fixes https://github.com/SymbiFlow/prjxray/issues/247
Fixes https://github.com/SymbiFlow/prjxray/issues/242
> parsedb tool, pushdb uses parsedb

- utils/environment.sh
fixes https://github.com/SymbiFlow/prjxray/issues/253
> environment.sh: fix PYTHONPATH

- README.md
> readme: add pip note

- utils/dbfixup.py
> dbfixup: missing arg on --clb-int

- prjxray/util.py
Current check works for most but not all bits. Breaks in 050 fuzzer
> parse_db_line: looser validation

- fuzzers/007-timing/minitest/test_unique/Makefile
- fuzzers/010-lutinit/Makefile
- fuzzers/019-ndi1mux/Makefile
- fuzzers/025-bram-config/Makefile
- fuzzers/026-bram-data/Makefile
- fuzzers/050-intpips/Makefile
- fuzzers/050-intpips/generate.sh
- fuzzers/050-intpips/generate.tcl
- fuzzers/051-imuxlout/Makefile
- fuzzers/052-clkin/Makefile
- fuzzers/053-ctrlin/Makefile
- fuzzers/054-gfan/Makefile
- fuzzers/055-gnd/Makefile
- fuzzers/056-rempips/Makefile
- fuzzers/057-bipips/Makefile
- fuzzers/058-hclkpips/Makefile
- fuzzers/100-dsp-mskpat/Makefile
This is causing issues right now since dbfixup requires files named like they are in the database dir
> Standardize db file name

- prjxray/util.py
- utils/dbfixup.py
- utils/mergedb.sh
- utils/parsedb.py
> db .py fixes

- utils/dbfixup.py
> dbfixup: quick hacks to make 050 happy

- Makefile
This partially fixes https://github.com/SymbiFlow/prjxray/issues/120
> make format: pin clang-format ver

- docs/format/db.rst
> db.rst: add -m/-M doc

- fuzzers/010-lutinit/.gitignore
- fuzzers/010-lutinit/Makefile
- fuzzers/010-lutinit/generate.sh
- fuzzers/010-lutinit/generate.tcl
- fuzzers/051-imuxlout/Makefile
- fuzzers/052-clkin/Makefile
- fuzzers/053-ctrlin/Makefile
- fuzzers/054-gfan/Makefile
- fuzzers/055-gnd/Makefile
- fuzzers/056-rempips/generate.py
- fuzzers/057-bipips/Makefile
- fuzzers/058-hclkpips/Makefile
- fuzzers/100-dsp-mskpat/Makefile
Mostly fixes https://github.com/SymbiFlow/prjxray/issues/276
Last time I tried to fix this I was conservative trying not to break fuzzers, but it seems I missed some of these. So this time I've just tried to replace everything. I ran most of the fuzzers last night, so I think most of the changes should be tested
056 will be addressed in a separate commit
> seg_ => segbits_

- prjxray/segmaker.py
> Segmaker checks

- fuzzers/050-intpips/Makefile
This possibly fixes https://github.com/SymbiFlow/prjxray/issues/289
> intpips: inrease N to reduce faulty solves

- prjxray/segmaker.py
> Improving assert error messages.

- fuzzers/int_loop.mk
- fuzzers/int_loop.sh
- fuzzers/int_loop_check.py
Fixes https://github.com/SymbiFlow/prjxray/issues/272
(sort of, it will time out instead of hanging)
Adds timeout capability to iterative fuzzers
> int_loop.mk: timeout

- fuzzers/050-intpips/.gitignore
- fuzzers/050-intpips/Makefile
- fuzzers/050-intpips/generate.sh
- fuzzers/050-intpips/generate.tcl
- fuzzers/050-intpips/maketodo.py
- fuzzers/056-rempips/maketodo.py
- fuzzers/int_loop.mk
- fuzzers/int_loop.sh
- fuzzers/int_loop_check.py
- fuzzers/piplist.tcl
- fuzzers/piplist.v
Provides finer grained controls and logging to control how many iterations we do, which influences the quality of results
> intpips iterative solver

- fuzzers/050-intpips/Makefile
- fuzzers/int_loop.mk
- fuzzers/int_loop.sh
Looks like its not needed. Possibly was supposed to be make MAKEFLAGS=$MAKEFLAGS instead of make $MAKEFLAGS
> Remove MAKEFLAGS

- fuzzers/050-intpips/Makefile
- fuzzers/int_maketodo.py
Regression where maketodo isn't being computed correctly in most looping fuzzers
> maketodo: normalize tile prefix

- fuzzers/050-intpips/Makefile
- fuzzers/int_loop.mk
Record the .db file on each iter. Currently the algorithm iterates on it, clobbering the last result
> Better int_loop logging

- .travis.yml
- Makefile
- lib/include/prjxray/xilinx/xc7series/configuration_bus.h
- lib/include/prjxray/xilinx/xc7series/global_clock_region.h
- lib/include/prjxray/xilinx/xc7series/row.h
- lib/xilinx/xc7series/configuration_test.cc
- tools/xc7patch.cc
- utils/environment.sh
- utils/tcl-reformat.sh
* Update to `clang-format-5.0`
* Use `yapf` from the environment if it exists.
> `make format` improvements

- Makefile
Fixes https://github.com/SymbiFlow/prjxray/issues/333
> make format: fix .git

- fuzzers/050-intpips/Makefile
Mitigation for https://github.com/SymbiFlow/prjxray/issues/331
> intpips: try harder, even though diminshing returns

- utils/dbfixup.py
Fixes https://github.com/SymbiFlow/prjxray/issues/348
May cause some fuzzers to (correctly?) fail
> dbfixup: fix zero enums

- fuzzers/005-tilegrid/Makefile
- fuzzers/005-tilegrid/iob/generate.sh
- prjxray/util.py
fixes https://github.com/SymbiFlow/prjxray/issues/345
Also improves make clean
> Iob dbroot

- Makefile
- README.md
* Fix the YAML check.
* Small update to README.
> Fix Python environment

- utils/genheader.sh
> genheader: set FUZDIR instead of per project

- fuzzers/055-gnd/Makefile
> 055-gnd/Makefile: fix bad clean

- fuzzers/100-dsp-mskpat/.gitignore
- fuzzers/100-dsp-mskpat/Makefile
- fuzzers/100-dsp-mskpat/generate.sh
- fuzzers/100-dsp-mskpat/generate.tcl
- fuzzers/Makefile
Fixes https://github.com/SymbiFlow/prjxray/issues/306
> Dsp mskpat build

- fuzzers/050-intpips/README.md
- fuzzers/056-rempips/README.md
Creating some better docs to understand issues in intpips/rempips
> Pip solvability notes

- fuzzers/056-rempips/generate.tcl
- utils/utils.tcl
This tries a few more times if the first tile positioning doesn't work out. Its unclear if this will help to me now, but it does at least prove that it won't if we get some failures. Additionally it will drop pips that it can't solve instead of completely halting. This should give us a much better idea of the pips that can be solved instead of it completely giving up
Also cleans up rempips print output a little
> rempips: try a few times to solve on failures

- fuzzers/050-intpips/.gitignore
- fuzzers/050-intpips/Makefile
- fuzzers/051-imuxlout/.gitignore
- fuzzers/052-clkin/.gitignore
- fuzzers/053-ctrlin/.gitignore
- fuzzers/054-gfan/.gitignore
- fuzzers/055-gnd/.gitignore
- fuzzers/056-rempips/.gitignore
- fuzzers/057-bipips/.gitignore
- fuzzers/int_loop.mk
- fuzzers/int_loop.sh
- fuzzers/int_loop_check.py
This tidies up the build and fixes a regression
> int_loop: mv todo build/todo

- Makefile
> Add checkdb target to top level Makefile.

- fuzzers/025-bram-config/Makefile
Fixes https://github.com/SymbiFlow/prjxray/issues/380
> bram: fix missing flag

- database/zynq7/settings.sh
This PR adds settings file for xc7z family.
> Added settings for Zynq FPGA SoC family

- fuzzers/050-intpips/README.md
- fuzzers/050-intpips/generate.py
Fixes https://github.com/SymbiFlow/prjxray/issues/383
Still testing, will merge once I finish regenerating .db. But quick result looks like this works as intended
> intpips: properly filter VCC_WIRE

- fuzzers/055-gnd/generate.tcl
Think this one was converted after the others to int_loop
> gnd: fix todo path

- fuzzers/int_loop.mk
Mitigation for https://github.com/SymbiFlow/prjxray/issues/389
> int_loop: unify SEGMATCH_FLAGS

- fuzzers/050-intpips/Makefile
int_loop.mk was changed, and this should have been as well
> intpips: cleaniter

- README.md
Signed-off-by: rapha <raphbeutel@gmail.com>
> added sudo to readme1

- download-latest-db.sh
This streamlines getting a cached DB while still doing fuzzer development
> download-latest: clean files

- requirements.txt
textx is required by roi_harness minitest
> Add textx packet to requirements.txt

- utils/environment.sh
- utils/vivado.sh
For https://github.com/SymbiFlow/prjxray/issues/14
> vivado: assert expected version

- htmlgen/htmlgen.py
> Fix htmlgen #173

- utils/segprint.py
Was claiming bits were unmatched, when they were in fact used
Also adds some spacing between -b output and later stages to make it more readable
> segprint: fix -b flag, working on tilegrid directly

- fuzzers/071-ppips/Makefile
- fuzzers/071-ppips/generate.sh
- fuzzers/071-ppips/generate.tcl
Correcting Bug #171 for Fuzzer 071.
Someone can verify it before merging ?
Signed-off-by: Mehdi Khairy <mehdi.khairy@more-magic.org>
> Bug #171: Fixing build directory for Fuzzers 071

- utils/mergedb.py
> Fix indenting in mergedb.py

- utils/segprint.py
> segprint: --bit-only

- fuzzers/025-bram-config/generate.py
fixes https://github.com/SymbiFlow/prjxray/issues/476
> bram config: DOX_REG, clean up

- .github/update-contributing.py
- .travis.yml
- CONTRIBUTING.md
- Makefile
- gridinfo/gridinfo-txt2json.py
- htmlgen/htmlgen.py
- prjxray/util.py
- requirements.txt
- tests/test_util.py
- utils/fasm2frames.py
- utils/simpleroute.py
- utils/test_fasm2frames.py
- utils/tileconnloops.py
- utils/tileconnwire.py
* Adds `make test` target which runs the tests.
* Add testing of Python code.
Travis now looks like this;
> Making tests run on travis

- fuzzers/052-pip-clkin/generate.tcl
Sometimes randomly selected scr and dst tiles lead to unroutable situation. This can be mitigated by repeating the failed attempt with a new src and dst tiles. Similar mechanism is used in fuzzer 056.
this fixes #496
> fuzzers: 52: retry routing if it fails

- fuzzers/052-pip-clkin/generate.py
- fuzzers/053-pip-ctrlin/generate.py
- fuzzers/057-pip-bi/generate.py
Lets see how they explode on Zynq.
> Remove asserts checking only artix7 / kintex7.

- fuzzers/074-dump_all/generate.sh
> fuzzers: 074: fix path to generate_after_dump

- fuzzers/int_loop.mk
> fuzzers: Copy all the db files to build/database

- fuzzers/057-pip-bi/generate.tcl
Sometimes the route_via failed.  Modeled this PR after #505 which solved a similar failure in 052.
> Add retries to bidirection PIP fuzzer.

- fuzzers/int_loop.mk
- settings/artix7.sh
- settings/kintex7.sh
- settings/zynq7.sh
- utils/environment.sh
this PR is a follow up to #520
> create empty db files if they don't exist

- fuzzers/005-tilegrid/Makefile
> Fix clean not working in 005-tilegrid

- minitests/roi_harness/runme.sh
> Call bit2fasm.py instead of bits2fasm.py

- fuzzers/clb.mk
Still seeing false matches, seeing if increase match requirement drives false rate to 0.
> Increase CLB match requirement.

- fuzzers/fuzzer.mk
> fuzzer.mk: remove not needed echo

- fuzzers/074-dump_all/Makefile
- fuzzers/074-dump_all/generate.sh
- fuzzers/074-dump_all/get_nodescount.tcl
- fuzzers/074-dump_all/get_tilescount.tcl
- fuzzers/074-dump_all/jobnodes.tcl
- fuzzers/074-dump_all/jobtiles.tcl
- fuzzers/074-dump_all/run_fuzzer.py
Need testing on that one it fails in tree generation:
```
100% (100 of 100) |###################################################################################################################################################################################| Elapsed Time: 0:00:12 Time:  0:00:12
+ python3 create_node_tree.py --dump_all_root_dir build/specimen_001/ --ordered_wires_root_dir ../072-ordered_wires/build/specimen_001/ --output_dir build/output
2019-01-15 18:07:25.242990 Reading root.csv
2019-01-15 18:07:28.248736 Loading node<->wire mapping
2019-01-15 18:07:30.598128 Creating wire<->node index
100% (3824221077 of 3824221077) |############################################################################################################################################################# …
```
> Reworking Fuzzer 074 for multi thread process

- fuzzers/074-dump_all/reduce_tile_types.py
- prjxray/node_lookup.py
This decreases memory usage significantly and is faster to boot!
> Refactor 074 post-processing

- fuzzers/072-ordered_wires/Makefile
- fuzzers/072-ordered_wires/generate.sh
- fuzzers/072-ordered_wires/run_fuzzer.py
This commit update the Fuzzer 072, adding arguments to control the number of parallel process from Makefile.
It should be close to 074.
For information the Zynq version of this fuzzer run in  15 to 20 minutes on 4 core. Need to be tested before merging.
> Adding modular arguments for parallel Fuzzer 072

- fuzzers/074-dump_all/run_fuzzer.py
Correct the Fuzzer 074 to generate correct file when total item is integer multiple of the int(nbBlocks)
> Fuzzer 074 support integer multiple of nbBlocks

- fuzzers/056-pip-rem/Makefile
> Increase 056 strictness.

- fuzzers/058-pip-hclk/Makefile
> pips-hclk: add run.ok to Makefile

- prjxray/segmaker.py
> Add frame limit to segmaker to prevent out of bound solutions.

- Makefile
- requirements.txt
- utils/cmp.py
- utils/info_md.py
- utils/sort_db.py
Adding a new `make formatdb` target to the Makefile and needed utils. The new target will,
* Canonicalize the database by running `./utils/sort_db.py`
* Regenerate the [`Info.md` file](database/Info.md)
> New `make formatdb` target

- fuzzers/019-clb-ndi1mux/Makefile
> Fuzzers: 019: set N=3

- fuzzers/clb.mk
- fuzzers/int_loop.mk
> fuzzers: Fix including Makefiles.

- fuzzers/005-tilegrid/README.md
Starting to look at improving some of the documentation of Project X-Ray.
> Makes minor documentation changes for tilegrid fuzzer

- fuzzers/100-dsp-mskpat/Makefile
> Revert Makefile changes, Fixes #582

- fuzzers/100-dsp-mskpat/Makefile
> Remove additional dependencies.

- fuzzers/053-pip-ctrlin/generate.tcl
- fuzzers/055-pip-gnd/generate.tcl
Fixes #613 
051 doesn't have retries, but I don't think we've seen a routing failure yet.
> Add retries to 053 and 055 INT fuzzers.

- Makefile
- requirements.txt
Much better fix than in https://github.com/SymbiFlow/prjxray/pull/616
> Install FASM into environment correctly

- .gitignore
- database/Makefile
- fuzzers/Makefile
- fuzzers/fuzzer.mk
- fuzzers/pip_loop.mk
- fuzzers/run_fuzzer.py
- requirements.txt
* Saves stdout / stderr to log files.
* Prefixes all messages with fuzzer name.
* Gives regular status updates.
> Adding wrapper to get understandable output.

- fuzzers/005-tilegrid/Makefile
- fuzzers/005-tilegrid/add_tdb.py
- fuzzers/005-tilegrid/cfg_int/Makefile
- fuzzers/005-tilegrid/cfg_int/generate.tcl
- fuzzers/005-tilegrid/cfg_int/top.py
- fuzzers/005-tilegrid/monitor_int/Makefile
- fuzzers/005-tilegrid/monitor_int/generate.tcl
- fuzzers/005-tilegrid/monitor_int/top.py
Fixes #618, and solves 2 of the 4 missing INT columns from #566 .
> Add XADC INT and ICAP INT fuzzers to solve 2 of 4 missing INT columns.

- .github/kokoro/db-full.sh
> infra: Improve the diff output.

- .github/autolabeler.yml
> Fixing the autolabeler configuration.

- tools/segmatch.cc
This PR is to solve https://github.com/SymbiFlow/prjxray/issues/338
> segmatch: added warning for missing files

- htmlgen/htmlgen.py
> Fix htmlgen for new settings file locations.

- .github/kokoro/database.cfg
- .github/kokoro/db-full.sh
- fuzzers/run_fuzzer.py
- Store output of logs rom run_fuzzer.py
- Decrease number of processes running for 072 and 074 to lower memory load.
This PR should be merged after #632
> Update CI configuration:

- fuzzers/050-pip-seed/Makefile
- fuzzers/050-pip-seed/generate.py
> Filter out FAN_ALT[0-9].GFAN[0-9] pips from 050.

- fuzzers/012-clb-n5ffmux/Makefile
- fuzzers/clb.mk
This PR fixes https://github.com/SymbiFlow/prjxray/issues/660.
> 012-clb-d5ff: increased specimens and added c argument

- fuzzers/029-bram-fifo-config/Makefile
this PR fixes https://github.com/SymbiFlow/prjxray/issues/658. I have run the fuzzer indefinitely for 1 hour waiting for a collision but it didn't fail. 
> 029-bram-fifo: more specimens and added c arg to segmatch

- fuzzers/042-clk-bufg-config/Makefile
- fuzzers/042-clk-bufg-config/generate.py
- fuzzers/042-clk-bufg-config/top.py
- prjxray/state_gen.py
> Simplify routing noise in 042

- fuzzers/060-bram-cascades/generate.py
Documents bits needed to fix https://github.com/SymbiFlow/symbiflow-arch-defs/issues/385
> Add CASCOUT_*_ACTIVE bits.

- README.md
> Small fix to README in license section.

- fuzzers/run_fuzzer.py
> Fix running without -j

- fuzzers/int_loop.sh
> fuzzers: int_loop: exit on empty todo

- fuzzers/005-tilegrid/generate_full.py
- prjxray/db.py
- prjxray/fasm_assembler.py
- prjxray/fasm_disassembler.py
- prjxray/grid.py
- prjxray/grid_types.py
- prjxray/tile_segbits.py
- prjxray/tile_segbits_alias.py
- utils/bit2fasm.py
This is my proposed solution to the IOB_SING issue.  This fixes #341 .  The idea is to explicitly have the IOB_SING tiles alias into the IOB tile type.  Currently segmaker does not understand this aliasing, but that is acceptable as IOB_SING tiles appear to pure subsets of IOB tiles.
> IOB_SING solution via segbit aliases.

- fuzzers/041-clk-hrow-pips/Makefile
- fuzzers/050-pip-seed/Makefile
- fuzzers/int_maketodo.py
- fuzzers/pip_loop.mk
Vivado expects to be executed in a unique directory in batch mode.
Previous Makefile had all piplist's running the same directory,
resulting in a race condition.
> Use seperate build directory for each piplist.

- fuzzers/Makefile
- utils/mergedb.sh
> utils: mergedb: lock database accesses

- fuzzers/007-timing/solve_linprog.py
- requirements.txt
> fuzzers: 007: fix linprog callback to fit scipy 1.2.1

- .github/kokoro/continuous-db-artix7.cfg
- .github/kokoro/continuous-db-kintex7.cfg
- .github/kokoro/continuous-db-zynq7.cfg
- .github/kokoro/db-full.sh
- .github/kokoro/kokoro-cfg.py
- .github/kokoro/presubmit-db-artix7.cfg
- .github/kokoro/presubmit-db-kintex7.cfg
- .github/kokoro/presubmit-db-zynq7.cfg
> infra: Fix the diff output.

- .github/kokoro/db-full.sh
(Plus include the stat at the top.)
> infra: Don't output color in .patch file

- fuzzers/041-clk-hrow-pips/Makefile
- fuzzers/048-int-piplist/Makefile
- fuzzers/pip_list.mk
- fuzzers/pip_loop.mk
Fixes #709 and helps with some INT fuzzer flakes.
> Fix 048 not using correct directory.

- fuzzers/Makefile
> Re-enable the DSP fuzzer.

- minitests/roi_harness/create_design_json.py
> add bits outside ROI to required features

- .github/kokoro/db-full.sh
- Makefile
Makes the patch produce by the CI system less confusing.
> Update info file on CI

- Makefile
Fixes regression from https://github.com/SymbiFlow/prjxray/pull/740
> Fix incorrect utility name.

- minitests/roi_harness/README.md
- minitests/roi_harness/arty-common.sh
- minitests/roi_harness/arty-pmod.sh
- minitests/roi_harness/arty-swbut.sh
- minitests/roi_harness/arty-uart.sh
- minitests/roi_harness/basys3-common.sh
- minitests/roi_harness/basys3-swbut.sh
- minitests/roi_harness/runme.tcl
- minitests/roi_harness/zybo-common.sh
- minitests/roi_harness/zybo-swbut.sh
Things which confused me while trying to regenerate the ROI harnesses.
> Improve the ROI harness reproducibility 

- htmlgen/htmlgen.py
All other types of tiles will now have a color.
Before:
After:
> htmlgen: Make sure only NULL+VBRK tiles are grey.

- docs/Makefile
> docs: Create the fuzzers + minitests directories.

- docs/architecture/bitstream_format.rst
Signed-off-by: Michael Gielda <mgielda@antmicro.com>
> docs: Fix some formatting

- README.md
Signed-off-by: Felix Held <felix-github@felixheld.de>
> README.md: clarify to not manually source the Vivado environment

- fuzzers/075-pins/Makefile
- fuzzers/075-pins/generate.sh
- fuzzers/075-pins/generate.tcl
- fuzzers/Makefile
> Add fuzzer for documenting pin to pad relationship for part.

- fuzzers/056-pip-rem/generate.tcl
This PR is part of the Stabilize prjxray output project
It is aimed at solving #714
> 056-pip-rem: lower PDIL-1 DRC severity

- Makefile
> Make Makefiles use bash shell

- .github/kokoro/continuous-db-artix7.cfg
- .github/kokoro/continuous-db-kintex7.cfg
- .github/kokoro/continuous-db-zynq7.cfg
- .github/kokoro/db-full.sh
- .github/kokoro/kokoro-cfg.py
- .github/kokoro/presubmit-db-artix7.cfg
- .github/kokoro/presubmit-db-kintex7.cfg
- .github/kokoro/presubmit-db-zynq7.cfg
> infra: Collect Vivado logs into tgz archive

- fuzzers/051-pip-imuxlout-bypalts/generate.tcl
- fuzzers/052-pip-clkin/generate.tcl
- fuzzers/053-pip-ctrlin/generate.tcl
- fuzzers/055-pip-gnd/generate.tcl
> fuzzers: Fix error usage

- fuzzers/054-pip-fan-alt/Makefile
- fuzzers/054-pip-fan-alt/README.md
This PR is part of the Stabilize prjxray output project
It is aimed at solving #567
> 054-pip-fan-alt: add BYP_ALT.GFAN PIPs calculation to fuzzer

- .gitmodules
- Makefile
- fuzzers/007-timing/Makefile
- fuzzers/007-timing/bel/.gitignore
- fuzzers/007-timing/bel/Makefile
- fuzzers/007-timing/bel/runme.sh
- fuzzers/007-timing/bel/runme.tcl
- fuzzers/007-timing/bel/tim2json.py
- fuzzers/007-timing/bel/top.v
- fuzzers/Makefile
- utils/makesdf.py
- utils/sdfmerge.py
- utils/utils.tcl
This PR adds bel timing fuzzer. For now only Carry, LUT6 and FDRE BELs are handled. More to come
> fuzzers: Adding BEL timing fuzzer

- fuzzers/run_fuzzer.py
* Fix the doctests.
* Reduce the memory output to be one line.
* Fix issue when running without jobserver.
> Small updates to fuzzer output.

- utils/makesdf.py
Signed-off-by: Karol Gugala <kgugala@antmicro.com>
> utils: makesdf: sort the output

- fuzzers/007-timing/bel/Makefile
- fuzzers/007-timing/bel/properties_map.json
- fuzzers/007-timing/bel/tim2json.py
- utils/makesdf.py
- utils/sdfmerge.py
fixes #832 
fixes #833 
fixes #834
> BEL timings fixes

- prjxray/tile.py
There was an additional factor of 1000 sitting in my model that needed to be pushed to the library.
> Correct units factor on resistances.

- prjxray/timing.py
Travis complained about this in every other PR.
> Fix formatting

- .github/kokoro/db-full.sh
- fuzzers/074-dump_all/create_node_tree.py
- fuzzers/074-dump_all/jobtiles.tcl
- fuzzers/074-dump_all/reduce_tile_types.py
This is required for interconnect timing models.
> Add wire, pip, and site pin timing information.

- fuzzers/005-tilegrid/Makefile
- fuzzers/005-tilegrid/add_tdb.py
- fuzzers/005-tilegrid/cfg/Makefile
- fuzzers/005-tilegrid/cfg/generate.tcl
- fuzzers/005-tilegrid/cfg/top.py
The last unknown bits reported in #746 belong to the CFG_CENTER_MID tile.
This PR calculates the base address for the tile.
> 005-tilegrid: add CFG_CENTER_MID tile base address calculation

- database/Makefile
- fuzzers/007-timing/bel/tim2json.py
> 007-timing: Do not emit SDF files for sites with no timings.

- fuzzers/int_maketodo.py
This PR adds a mechanism for the creation of balanced todo lists.
Background
This mechanism is needed for fixing instability problems in some fuzzers which led to timeouts. 
The root cause of the timeout is that starting with a certain iteration the fuzzer (segmatch) was unable to find a clear solution for the PIPs from the todo list.
In a particular case (#784) the timeout was caused by the fact that the  PIPs with the ``CLK_HROW_CK_IN_`` source wire, e.g. ``CLK_HROW_BOT_R_CK_BUFG_CASCO7.CLK_HROW_CK_IN_L8`` had 3 candidate bits while the SEGMATCH_ARGS had the limiation set to 2 ( ``-c 2``). This is because in fact only two bits are for the ``CLK_HROW_BOT_R_CK_BUFG_CASCO7.CLK_HROW_CK_IN_L8`` PIP and the third bit is for ``CLK_HROW_CK_IN_L8_ACTIVE``.
In order for segmatch to solve the bits …
> Implement todo lists balancing mechanism

- fuzzers/005-tilegrid/Makefile
- fuzzers/005-tilegrid/add_tdb.py
- fuzzers/005-tilegrid/generate_full.py
- fuzzers/005-tilegrid/ioi/Makefile
- fuzzers/005-tilegrid/ioi/generate.tcl
- fuzzers/005-tilegrid/ioi/top.py
> Calculate base addresses for IOI tiles

- fuzzers/005-tilegrid/Makefile
- fuzzers/005-tilegrid/add_tdb.py
- fuzzers/005-tilegrid/generate_full.py
- fuzzers/005-tilegrid/hclk_ioi/Makefile
- fuzzers/005-tilegrid/hclk_ioi/generate.tcl
- fuzzers/005-tilegrid/hclk_ioi/top.py
> Calculate base addresses for HCLK_IOI3 tiles.

- fuzzers/005-tilegrid/mmcm/top.py
> fuzzers: tilegrid: mmcme: LOC mmcme2_adv instances

- fuzzers/015-clb-nffmux/Makefile
- fuzzers/015-clb-nffmux/generate.py
- fuzzers/015-clb-nffmux/top.py
- fuzzers/016-clb-noutmux/Makefile
- fuzzers/016-clb-noutmux/generate.py
- fuzzers/016-clb-noutmux/top.py
- fuzzers/clb_ext.mk
Modified fuzzer `015-clb-nffmux` and `016-clb-noutmux` to fuzz bits for `DFFMUX.MC31` and `DOUTMUX.MC31`
> Fuzzer for DOUTMUX.MC31 and DFFMUX.MC31

- fuzzers/int_loop_check.py
> int_loop_check.py: Fix output formatting

- fuzzers/036-iob-ologic/generate.py
- fuzzers/036-iob-ologic/top.py
This adds a couple features, but most importantly it documents some that were mistakenly associate with the 030 IOB fuzzer, which was fixed in #970.
> Add some additional OLOGIC bits.

- fuzzers/036-iob-ologic/generate.py
- fuzzers/036-iob-ologic/generate.tcl
- fuzzers/036-iob-ologic/top.py
This PR adds the `OSERDES.IN_USE` tag.
More info in this issue https://github.com/SymbiFlow/prjxray/issues/962.
> 036-ologic: add IN_USE oserdes

- fuzzers/030-iob/check_results.py
- fuzzers/030-iob/generate.py
- fuzzers/030-iob/generate.tcl
- fuzzers/030-iob/process_rdb.py
- fuzzers/030-iob/top.py
- Add IN_DIFF and OUT_DIFF features.
- Add IN_TERM features.
This appears to solve all remaining LiteX IOB bits in frames 38/39.
> Add initial DIFF_ support to IOB fuzzer.

- fuzzers/036-iob-ologic/generate.py
- Also prefix decimal features with A-Z
Fixes #962
> Add TSRTYPE features to OLOGIC fuzzer

- minitests/litex/src.yosys/missing_bit_report.py
This report is fairly fragile, but works well enough for the remaining
LiteX bits.
> Create script for generating remaining LiteX bit report.

- fuzzers/000-init-db/Makefile
- fuzzers/047-hclk-ioi-pips/generate.py
- fuzzers/047-hclk-ioi-pips/hclk_ioi3_pip_list.tcl
Solves 4 of the remaining 10 HCLK_IOI3 bits.
> Relax pip filtering to find additional HCLK_IOI3 pip bits.

- fuzzers/int_maketodo.py
> Restore int_maketodo support for non-LR sides.

- fuzzers/030-iob/Makefile
- fuzzers/030-iob/generate.py
- fuzzers/030-iob/top.py
- fuzzers/030-iob/write_io_banks.tcl
> Add HCLK_IOI3.INTERNAL_VREF feature.

- fuzzers/037-iob-pips/Makefile
- fuzzers/037-iob-pips/generate.py
- fuzzers/037-iob-pips/ioi3_pip_list.tcl
- fuzzers/037-iob-pips/top.py
- Also relaxes pip list filtering to capture additional bits.
> Solve OCLKM pips in IOI3

- fuzzers/037-iob-pips/Makefile
- fuzzers/037-iob-pips/generate.tcl
- fuzzers/037-iob-pips/top.py
This does lose the IMUX->OCLKM pip, but I believe that is okay. That pip
was returning an incorrect solution anyways.
> Refactor 037 to remove some unstable pips.

- UPDATING-THE-DOCS.md
Signed-off-by: Michael Gielda <mgielda@antmicro.com>
> Update the UPDATING THE DOCS doc

- minitests/plle2_adv/Makefile
- minitests/plle2_adv/README.md
- minitests/plle2_adv/basys3.xdc
- minitests/plle2_adv/basys3_plle2_adv.v
- minitests/plle2_adv/src/plle2_test.v
- minitests/plle2_adv/tcl/par.tcl
- minitests/plle2_adv/tcl/syn.tcl
A minitest for the PLLE2_ADV. Multiple LEDs driven by PLL outputs.
> Minitest for PLLE2_ADV

- docs/conf.py
- docs/requirements.txt
This PR changes the theme used in Sphinx from Symbiflow to Material Design.
> Change theme to Sphinx Material Design

- fuzzers/005-tilegrid/Makefile
- fuzzers/005-tilegrid/generate.py
- fuzzers/005-tilegrid/generate_tiles.tcl
- prjxray/fasm_assembler.py
- prjxray/grid.py
- prjxray/grid_types.py
- utils/fasm2frames.py
- Add support to emit PUDC_B pullup if unused (for A7 and Z7 fabrics).
> Add pin functions to tilegrid.

- CMakeLists.txt
- lib/include/prjxray/xilinx/architectures.h
> Fixes to enable compilation under clang-7.

- fuzzers/005-tilegrid/generate_full.py
This addresses issue found in https://github.com/SymbiFlow/symbiflow-arch-defs/pull/1105#issuecomment-545444163
> Add HCLK_[LR]_BOT_UTURN aliases.

- minitests/litex_litedram/src.vivado/verilog/VexRiscv.v
- minitests/litex_litedram/src.yosys/verilog/VexRiscv.v
> Fix trailing white space.

- fuzzers/071-ppips/generate.tcl
There are some `fake` PPIPs relative to the HCLK_IOI3 tile that are added if no filter is applied.
This PR prevents some real pips to be added to the PPIPs list.
This fix is needed for the [OSERDES PR](https://github.com/SymbiFlow/symbiflow-arch-defs/pull/1102) to correctly configure the input clocks.
> 071-ppips: skip HCLK_IOI_CK_IGCLK[0-9] ppips addition

- fuzzers/032-cmt-pll/generate.py
- fuzzers/032-cmt-pll/generate.tcl
- fuzzers/032-cmt-pll/top.py
- fuzzers/034-cmt-pll-pips/fixup_and_group.py
Fixes https://github.com/SymbiFlow/prjxray/issues/1141
> Update to 032 which fixes conflict with 034

- fuzzers/071-ppips/generate.tcl
This PR solves this issue: https://github.com/SymbiFlow/symbiflow-arch-defs/pull/1174#issuecomment-561720803.
There is a ppip that shouldn't be added within the IOI tiles:
```
LIOI3.LIOI_IDELAY0_DATAOUT.LIOI_IDELAY0_IDATAIN always
```
> 071-ppips: fix wrong ppip in ioi tiles

- .github/kokoro/db-full.sh
If the diff is very large, don't do a couple of things;
* Output the patch into the console log.
* Generate a pretty HTML version of the diff.
> kokoro: Behave better on large diffs.

- fuzzers/100-dsp-mskpat/generate.py
- fuzzers/100-dsp-mskpat/top.py
Still not perfect, but with this there are enough bits known that a simple combinational DSPs (at least) can go through pnr and bitgen
> fuzzers: Improve DSP fuzzer

- htmlgen/htmlgen.py
> Fix htmlgen for changing DB structure.

- Makefile
> Add xc7a35tftg256 package to extra output.

- fuzzers/007-timing/bel/Makefile
- fuzzers/007-timing/bel/fixup_timings_txt.py
- fuzzers/007-timing/bel/runme.tcl
- fuzzers/007-timing/bel/tim2json.py
- requirements.txt
This only modified the tcl to change the output, but it immediately causes the post-processing script to fail.  @kgugala Can you see if you work out what is up?  The post-processing script needs some work, as it is currently very hard to understand or maintain.
> I/OSERDES BEL timing

- fuzzers/030-iob/generate.py
- fuzzers/030-iob/write_io_banks.tcl
Fixed the 030 fuzzer to automatically detect where the PUDC_B site is.
> Fix for the lost IOB bits

- .github/kokoro/db-full.sh
- .github/kokoro/steps/hostinfo.sh
- .gitignore
- Makefile
- fuzzers/000-init-db/Makefile
- fuzzers/001-part-yaml/Makefile
- fuzzers/005-tilegrid/Makefile
- fuzzers/005-tilegrid/add_tdb.py
- fuzzers/005-tilegrid/cfg_int/Makefile
- fuzzers/005-tilegrid/fuzzaddr/common.mk
- fuzzers/005-tilegrid/fuzzaddr/generate.sh
- fuzzers/005-tilegrid/generate.py
- fuzzers/005-tilegrid/generate_tiles.tcl
- fuzzers/072-ordered_wires/Makefile
- fuzzers/073-get_counts/Makefile
- fuzzers/074-dump_all/Makefile
- fuzzers/074-dump_all/generate_after_dump.sh
- fuzzers/074-dump_all/generate_grid.py
- fuzzers/074-dump_all/get_speed_model.tcl
- fuzzers/074-dump_all/jobtiles.tcl
- fuzzers/074-dump_all/reduce_tile_types.py
- fuzzers/074-dump_all/run_fuzzer.py
- fuzzers/075-pins/Makefile
- fuzzers/Makefile
- fuzzers/run_fuzzer.py
- minitests/roi_harness/Makefile
Variant of #1220 with some attempts at fixing failures.
> Optimize 074 dump all

- minitests/litex/min/arty/src.yosys/Makefile
- minitests/litex/min_ddr/arty/src.yosys/Makefile
- minitests/litex/src.yosys/Makefile
- minitests/litex_litedram/src.yosys/Makefile
> minitests/litex*: Fix location of clean_json5.py tool.

- docs/architecture/bitstream_format.rst
Working on adding more details to the bitstream format chapter of the Prjxray doc
> Documentation: Extend bitstream format chapter

- docs/architecture/interconnect.rst
- docs/conf.py
- docs/db_dev_process/fuzzers/index.rst
- docs/db_dev_process/minitests/index.rst
- docs/index.rst
- fuzzers/038-cfg/README.md
This commit resolves all warnings in the project documentation.
> Fix warnings in documentation

- fuzzers/045-hclk-cmt-pips/Makefile
- fuzzers/045-hclk-cmt-pips/generate.py
- fuzzers/045-hclk-cmt-pips/generate.tcl
- fuzzers/045-hclk-cmt-pips/top.py
This PR enhances 045 so it now can solve the following PIPs:
```
HCLK_CMT_FREQ_REF_NS0.HCLK_CMT_MUX_OUT_FREQ_REF0
HCLK_CMT_FREQ_REF_NS1.HCLK_CMT_MUX_OUT_FREQ_REF1
HCLK_CMT_FREQ_REF_NS2.HCLK_CMT_MUX_OUT_FREQ_REF2
HCLK_CMT_FREQ_REF_NS3.HCLK_CMT_MUX_OUT_FREQ_REF3
HCLK_CMT_MUX_OUT_FREQ_REF0.HCLK_CMT_CCIO0
HCLK_CMT_MUX_OUT_FREQ_REF0.HCLK_CMT_MUX_CLKINT_0
HCLK_CMT_MUX_OUT_FREQ_REF1.HCLK_CMT_CCIO1
HCLK_CMT_MUX_OUT_FREQ_REF1.HCLK_CMT_MUX_CLKINT_1
HCLK_CMT_MUX_OUT_FREQ_REF2.HCLK_CMT_CCIO2
HCLK_CMT_MUX_OUT_FREQ_REF2.HCLK_CMT_MUX_CLKINT_2
HCLK_CMT_MUX_OUT_FREQ_REF3.HCLK_CMT_CCIO3
HCLK_CMT_MUX_OUT_FREQ_REF3.HCLK_CMT_MUX_CLKINT_3
```
> Enhanced 045 to solve FREQ_REF related PIPs

- Makefile
- setup.py
- tools/CMakeLists.txt
- utils/checkdb.py
- utils/sort_db.py
- utils/test_fasm2frames.py
This PR adds a cmake command to install the built tools. This is needed to have prjxray set as a conda package.
> Adds installation of Xray tools

- CONTRIBUTING.md
- README.md
This PR fixes some links in README.md
I'm not sure why there are changes from dependabot (third_party/cctz) in my commit...
Signed-off-by: Dominik Wernberger <dominik2.wernberger@tum.de>
> Fix some links

- lib/memory_mapped_file.cc
An alternate PR for https://github.com/SymbiFlow/prjxray/pull/1360
> remove MAP_POPULATE

- fuzzers/007-timing/routing-bels/tim2sdf.py
> Fix SDF generation

- README.md
> Adding build badges.

- .github/kokoro/steps/hostsetup.sh
- Makefile
- fuzzers/018-clb-ram/Makefile
- fuzzers/018-clb-ram/top.py
- prjxray/tile_segbits.py
- requirements.txt
- utils/dbfixup.py
- utils/environment.python.sh
@mkurc-ant This probably needs to be fixed in prjuray-tools too.  Another reason to converge the repos when we can.
> Fix python on kokoro and break circular import through tile_segbits.

- fuzzers/005-tilegrid/add_tdb.py
- fuzzers/005-tilegrid/pll/Makefile
- fuzzers/034-cmt-pll-pips/cmt_top_upper_t.tcl
- fuzzers/034-cmt-pll-pips/fixup_and_group.py
- fuzzers/034-cmt-pll-pips/generate.py
- fuzzers/034-cmt-pll-pips/generate.tcl
This helps with https://github.com/SymbiFlow/symbiflow-arch-defs/issues/1536
This adds `CMT_TOP_R_UPPER_T.PLL_CLK_FREQ_BB[0-3]_NS_ACTIVE`
> Add missing FREQ_BB active feature

- fuzzers/035b-iob-iserdes/Makefile
- fuzzers/035b-iob-iserdes/generate.py
- fuzzers/035b-iob-iserdes/top.py
- fuzzers/044-clk-bufg-pips/Makefile
- utils/dbfixup.py
- utils/mergedb.sh
This addresses missing features in https://github.com/SymbiFlow/symbiflow-arch-defs/issues/1536
> Add IFF.IN_USE feature.

- docs/requirements.txt
See https://github.com/pypa/pip/issues/9031 for way too many details.
> Fixup doc requirements to work around https://github.com/pypa/pip/issues/9031

- fuzzers/027-bram36-config/Makefile
- fuzzers/027-bram36-config/README.md
- fuzzers/027-bram36-config/generate.py
- fuzzers/027-bram36-config/top.py
This fixes the BRAM features for https://github.com/SymbiFlow/symbiflow-arch-defs/pull/1720
> Fix new BRAM36 features.

- fuzzers/031-cmt-mmcm/generate.py
- fuzzers/031-cmt-mmcm/generate.tcl
- fuzzers/031-cmt-mmcm/top.py
This PR fixes bit conflict between the `IN_USE` feature solved by 031 and some PIPs solved by 034b. It also adds solution of some more `MMCME2` features (parameters):
- `ZINV_PSEN` (for IS_PSEN_INVERTED)
- `ZINV_PSINCDEC` (for IS_PSINCDEC_INVERTED)
- `SS_EN`
> MMCM bit conflict fix

- fuzzers/034b-cmt-mmcm-pips/fixup_and_group.py
This PR enables solution for MMCM REBUF PIPs.
> Enable MMCM REBUF PIPs

- lib/include/prjxray/xilinx/bitstream_reader.h
- tools/bits2rbt/configuration_packets.h
- tools/bits2rbt/header.cc
This PR fixes the wrong formatting in `bits2rbt` in the current master.
Here is the link to the currently failing CI:
https://github.com/SymbiFlow/prjxray/runs/1514803627
> format: Fix formating in bits2rbt

- fuzzers/005-tilegrid/Makefile
- fuzzers/005-tilegrid/add_tdb.py
- fuzzers/005-tilegrid/pcie/Makefile
- fuzzers/005-tilegrid/pcie/generate.tcl
- fuzzers/005-tilegrid/pcie/top.py
This PR adds the PCIE_BOT baseaddress to the tilegrid. It addresses https://github.com/SymbiFlow/prjxray/issues/1542
> pcie: add to tilegrid

- fuzzers/run_fuzzer.py
- settings/artix7.sh
- settings/artix7_200t.sh
- settings/artix7_50t.sh
- settings/kintex7.sh
- settings/zynq7.sh
- settings/zynq7010.sh
- utils/create_environment.py
This PR fixes https://github.com/SymbiFlow/prjxray/issues/1557
> environment: fix environment set up

- fuzzers/005-tilegrid/Makefile
- fuzzers/005-tilegrid/add_tdb.py
- fuzzers/005-tilegrid/gtp_channel/Makefile
- fuzzers/005-tilegrid/gtp_channel/generate.tcl
- fuzzers/005-tilegrid/gtp_channel/top.py
This PR adds the tilegrid fuzzer for the GTP_CHANNEL tiles.
> 005-tilegrid: Add GTP_CHANNEL tilegrid fuzzer

- minitests/litex/nexys_video_sata/.gitignore
- minitests/litex/nexys_video_sata/Makefile
- minitests/litex/nexys_video_sata/README.md
- minitests/litex/nexys_video_sata/requirements.txt
- minitests/litex/nexys_video_sata/retarget.v
- minitests/litex/nexys_video_sata/tcl/par.tcl
- minitests/litex/nexys_video_sata/tcl/syn.tcl
This PR is to add a LiteX minitest that makes use of liteSATA, which implements the GTP-related tiles
> minitest: add lite-sata minitest to verify GTP status

- README.md
> Add directory to repository cloning step

- fuzzers/005-tilegrid/Makefile
- fuzzers/005-tilegrid/add_tdb.py
- fuzzers/005-tilegrid/generate_full.py
- fuzzers/005-tilegrid/gtp_int_interface/generate.tcl
- fuzzers/005-tilegrid/pcie_int_interface/Makefile
- fuzzers/005-tilegrid/pcie_int_interface/generate.tcl
- fuzzers/005-tilegrid/pcie_int_interface/top.py
> 005-tilegrid: add pcie_int_interface tile baseaddrs

- fuzzers/030-iob/Makefile
- fuzzers/030-iob/generate.py
- fuzzers/030-iob/process_rdb.py
- fuzzers/030-iob/top.py
> 030-iob: add LVDS_25 and TMDS_33

- fuzzers/030-iob/process_rdb.py
Fixes issue found in https://github.com/SymbiFlow/prjxray/pull/1587#issuecomment-781507948
> 030-iob: improve rdb processing for LVDS and TMDS

- fuzzers/071-ppips/generate.tcl
> 071-ppips: add missing GTP-related PPIPs

- fuzzers/031-cmt-mmcm/write_mmcm_reg.py
- fuzzers/032-cmt-pll/write_pll_reg.py
- fuzzers/063-gtp-common-conf/generate.py
- prjxray/segmaker.py
> segmaker: fix site_type prefixes for GTP sites

- fuzzers/071-ppips/generate.tcl
There were some uncaught differences with the PIPs between the GTP_MID and normal GTP tiles. This PR should add all of the missing PPIPs.
> 071-ppips: additional fix for GTP-related PPIPs

- fuzzers/063-gtp-common-conf/generate.py
- fuzzers/063-gtp-common-conf/top.py
- fuzzers/064-gtp-channel-conf/generate.py
- fuzzers/064-gtp-channel-conf/top.py
> gtp: fix inverted signals. Change ZINV feature to INV

- fuzzers/030-iob/process_rdb.py
This PR fixes a problem with the current iob fuzzer. Basically, the newly added LVDS_25 and TMDS_33 iostandards do appear only in the IOB_Y0 site, making the features un-balanced in the two sites.
Before this PR:
```
LIOB33.IOB_Y1.LVCMOS12_LVCMOS15_LVCMOS18_LVCMOS25_LVCMOS33_LVTTL_SSTL135_SSTL15.IN_ONLY
LIOB33.IOB_Y0.LVCMOS12_LVCMOS15_LVCMOS18_LVCMOS25_LVCMOS33_LVDS_25_LVTTL_SSTL135_SSTL15_TMDS_33.IN_ONLY
```
With this PR:
```
LIOB33.IOB_Y1.LVCMOS12_LVCMOS15_LVCMOS18_LVCMOS25_LVCMOS33_LVDS_25_LVTTL_SSTL135_SSTL15_TMDS_33.IN_ONLY
LIOB33.IOB_Y0.LVCMOS12_LVCMOS15_LVCMOS18_LVCMOS25_LVCMOS33_LVDS_25_LVTTL_SSTL135_SSTL15_TMDS_33.IN_ONLY
```
> 030-iob: fix un-even features in different sites

- fuzzers/071-ppips/generate.tcl
Avoid using whitelists, and add PPIPs based on number of uphill connections.
Using whitelists to filter in the correct PPIPs to take proved to be complex to manage, as some of the PPIPs were not correctly identified.
The problem is that GTP_COMMON and GTP_COMMON_MID tiles do have slightly different PIPs around the wires corresponding to clock sources.
> 071-ppips: take all ppips with one uphill nodes

- fuzzers/071-ppips/generate.tcl
Signed-off-by: Jan Kowalewski <jkowalewski@antmicro.com>
> 071-ppips: add pcie-related ppips

- .github/kokoro/steps/hostcheck.sh
Based on https://github.com/SymbiFlow/prjxray/pull/1632 with the addition of https://github.com/SymbiFlow/prjxray/pull/1632#issuecomment-805061272
> Fix hostcheck

- docs/dev_database/common/cell_data.rst
- fuzzers/061-pcie-conf/generate_ports.tcl
- fuzzers/063-gtp-common-conf/generate_ports.tcl
- fuzzers/064-gtp-channel-conf/attrs.json
- fuzzers/064-gtp-channel-conf/generate_ports.tcl
- utils/make_ports.py
- utils/update_resources.py
- utils/update_resources.tcl
- utils/utils.tcl
It is useful to have also the information whether a port is a clock in the cells_data files
> cells_data: add clock information on ports.json

- docs/db_dev_process/newpart.rst
- settings/artix7.sh
- settings/artix7_200t.sh
- settings/artix7_50t.sh
- settings/kintex7.sh
- settings/zynq7.sh
- settings/zynq7010.sh
Based on the last two comments from https://github.com/SymbiFlow/prjxray/pull/1627#pullrequestreview-626463563
> Minor fixups for #1627

- fuzzers/071-ppips/generate.tcl
> 071-ppips: add LIOB33 and RIOB33 ppips

- fuzzers/005-tilegrid/Makefile
* Make clear the device specific fuzzers.
* Make clear the DSPs being disabled for Kintex7
Signed-off-by: Tim 'mithro' Ansell <tansell@google.com>
> Small fix to fuzzer makefile.

- fuzzers/005-tilegrid/Makefile
Signed-off-by: Tim 'mithro' Ansell <tansell@google.com>
> Try running DSP fuzzers on Kintex7.

- .github/workflows/database.yml
- .github/workflows/tests.yml
- README.md
This also updates the README badges
> ci: separate test and database in different workflows

- .github/dependabot.yml
Ref https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#directory
> dependabot: handle github-actions

- fuzzers/011-clb-ffconfig/README.md
The FDSE and FDRE are the elements with synchronous resets.
> fuzzers: fix typo in 011-clb-ffconfig README

- README.md
Signed-off-by: Bastian Löher <me@l-dot.de>
> Update README.md link to f4pga readthedocs

- lib/include/prjxray/big_endian_span.h
- lib/include/prjxray/segbits_file_reader.h
- lib/include/prjxray/xilinx/bitstream_reader.h
- lib/include/prjxray/xilinx/bitstream_writer.h
Updated the code which was using the std::iterator class, which has been marked as deprecated in the C++17 standard
> Updated iterator class
